<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>ObservableOnErrorResumeNextViaFunctionTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.operators.observable</a> &gt; <span class="el_source">ObservableOnErrorResumeNextViaFunctionTest.java</span></div><h1>ObservableOnErrorResumeNextViaFunctionTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.operators.observable;

import static org.junit.Assert.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

import java.io.IOException;
import java.util.concurrent.atomic.AtomicReference;

import org.junit.*;
import org.mockito.Mockito;
import org.reactivestreams.Subscription;

import io.reactivex.*;
import io.reactivex.disposables.*;
import io.reactivex.functions.Function;
import io.reactivex.internal.functions.Functions;
import io.reactivex.observers.*;
import io.reactivex.schedulers.Schedulers;

<span class="fc" id="L34">public class ObservableOnErrorResumeNextViaFunctionTest {</span>

    @Test
    public void testResumeNextWithSynchronousExecution() {
<span class="fc" id="L38">        final AtomicReference&lt;Throwable&gt; receivedException = new AtomicReference&lt;Throwable&gt;();</span>
<span class="fc" id="L39">        Observable&lt;String&gt; w = Observable.unsafeCreate(new ObservableSource&lt;String&gt;() {</span>

            @Override
            public void subscribe(Observer&lt;? super String&gt; observer) {
<span class="fc" id="L43">                observer.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L44">                observer.onNext(&quot;one&quot;);</span>
<span class="fc" id="L45">                observer.onError(new Throwable(&quot;injected failure&quot;));</span>
<span class="fc" id="L46">                observer.onNext(&quot;two&quot;);</span>
<span class="fc" id="L47">                observer.onNext(&quot;three&quot;);</span>
<span class="fc" id="L48">            }</span>
        });

<span class="fc" id="L51">        Function&lt;Throwable, Observable&lt;String&gt;&gt; resume = new Function&lt;Throwable, Observable&lt;String&gt;&gt;() {</span>

            @Override
            public Observable&lt;String&gt; apply(Throwable t1) {
<span class="fc" id="L55">                receivedException.set(t1);</span>
<span class="fc" id="L56">                return Observable.just(&quot;twoResume&quot;, &quot;threeResume&quot;);</span>
            }

        };
<span class="fc" id="L60">        Observable&lt;String&gt; observable = w.onErrorResumeNext(resume);</span>

<span class="fc" id="L62">        Observer&lt;String&gt; observer = TestHelper.mockObserver();</span>

<span class="fc" id="L64">        observable.subscribe(observer);</span>

<span class="fc" id="L66">        verify(observer, Mockito.never()).onError(any(Throwable.class));</span>
<span class="fc" id="L67">        verify(observer, times(1)).onComplete();</span>
<span class="fc" id="L68">        verify(observer, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L69">        verify(observer, Mockito.never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L70">        verify(observer, Mockito.never()).onNext(&quot;three&quot;);</span>
<span class="fc" id="L71">        verify(observer, times(1)).onNext(&quot;twoResume&quot;);</span>
<span class="fc" id="L72">        verify(observer, times(1)).onNext(&quot;threeResume&quot;);</span>
<span class="fc" id="L73">        assertNotNull(receivedException.get());</span>
<span class="fc" id="L74">    }</span>

    @Test
    public void testResumeNextWithAsyncExecution() {
<span class="fc" id="L78">        final AtomicReference&lt;Throwable&gt; receivedException = new AtomicReference&lt;Throwable&gt;();</span>
<span class="fc" id="L79">        Subscription s = mock(Subscription.class);</span>
<span class="fc" id="L80">        TestObservable w = new TestObservable(s, &quot;one&quot;);</span>
<span class="fc" id="L81">        Function&lt;Throwable, Observable&lt;String&gt;&gt; resume = new Function&lt;Throwable, Observable&lt;String&gt;&gt;() {</span>

            @Override
            public Observable&lt;String&gt; apply(Throwable t1) {
<span class="fc" id="L85">                receivedException.set(t1);</span>
<span class="fc" id="L86">                return Observable.just(&quot;twoResume&quot;, &quot;threeResume&quot;);</span>
            }

        };
<span class="fc" id="L90">        Observable&lt;String&gt; o = Observable.unsafeCreate(w).onErrorResumeNext(resume);</span>

<span class="fc" id="L92">        Observer&lt;String&gt; observer = TestHelper.mockObserver();</span>

<span class="fc" id="L94">        o.subscribe(observer);</span>

        try {
<span class="fc" id="L97">            w.t.join();</span>
<span class="nc" id="L98">        } catch (InterruptedException e) {</span>
<span class="nc" id="L99">            fail(e.getMessage());</span>
<span class="fc" id="L100">        }</span>

<span class="fc" id="L102">        verify(observer, Mockito.never()).onError(any(Throwable.class));</span>
<span class="fc" id="L103">        verify(observer, times(1)).onComplete();</span>
<span class="fc" id="L104">        verify(observer, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L105">        verify(observer, Mockito.never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L106">        verify(observer, Mockito.never()).onNext(&quot;three&quot;);</span>
<span class="fc" id="L107">        verify(observer, times(1)).onNext(&quot;twoResume&quot;);</span>
<span class="fc" id="L108">        verify(observer, times(1)).onNext(&quot;threeResume&quot;);</span>
<span class="fc" id="L109">        assertNotNull(receivedException.get());</span>
<span class="fc" id="L110">    }</span>

    /**
     * Test that when a function throws an exception this is propagated through onError.
     */
    @Test
    public void testFunctionThrowsError() {
<span class="fc" id="L117">        Subscription s = mock(Subscription.class);</span>
<span class="fc" id="L118">        TestObservable w = new TestObservable(s, &quot;one&quot;);</span>
<span class="fc" id="L119">        Function&lt;Throwable, Observable&lt;String&gt;&gt; resume = new Function&lt;Throwable, Observable&lt;String&gt;&gt;() {</span>

            @Override
            public Observable&lt;String&gt; apply(Throwable t1) {
<span class="fc" id="L123">                throw new RuntimeException(&quot;exception from function&quot;);</span>
            }

        };
<span class="fc" id="L127">        Observable&lt;String&gt; o = Observable.unsafeCreate(w).onErrorResumeNext(resume);</span>

<span class="fc" id="L129">        Observer&lt;String&gt; observer = TestHelper.mockObserver();</span>
<span class="fc" id="L130">        o.subscribe(observer);</span>

        try {
<span class="fc" id="L133">            w.t.join();</span>
<span class="nc" id="L134">        } catch (InterruptedException e) {</span>
<span class="nc" id="L135">            fail(e.getMessage());</span>
<span class="fc" id="L136">        }</span>

        // we should get the &quot;one&quot; value before the error
<span class="fc" id="L139">        verify(observer, times(1)).onNext(&quot;one&quot;);</span>

        // we should have received an onError call on the Observer since the resume function threw an exception
<span class="fc" id="L142">        verify(observer, times(1)).onError(any(Throwable.class));</span>
<span class="fc" id="L143">        verify(observer, times(0)).onComplete();</span>
<span class="fc" id="L144">    }</span>

    /**
     * Test that we receive the onError if an exception is thrown from an operator that
     * does not have manual try/catch handling like map does.
     */
    @Test
    @Ignore(&quot;Failed operator may leave the child Observer in an inconsistent state which prevents further error delivery.&quot;)
    public void testOnErrorResumeReceivesErrorFromPreviousNonProtectedOperator() {
<span class="nc" id="L153">        TestObserver&lt;String&gt; to = new TestObserver&lt;String&gt;();</span>
<span class="nc" id="L154">        Observable.just(1).lift(new ObservableOperator&lt;String, Integer&gt;() {</span>

            @Override
            public Observer&lt;? super Integer&gt; apply(Observer&lt;? super String&gt; t1) {
<span class="nc" id="L158">                throw new RuntimeException(&quot;failed&quot;);</span>
            }

<span class="nc" id="L161">        }).onErrorResumeNext(new Function&lt;Throwable, Observable&lt;String&gt;&gt;() {</span>

            @Override
            public Observable&lt;String&gt; apply(Throwable t1) {
<span class="nc bnc" id="L165" title="All 2 branches missed.">                if (t1.getMessage().equals(&quot;failed&quot;)) {</span>
<span class="nc" id="L166">                    return Observable.just(&quot;success&quot;);</span>
                } else {
<span class="nc" id="L168">                    return Observable.error(t1);</span>
                }
            }

<span class="nc" id="L172">        }).subscribe(to);</span>

<span class="nc" id="L174">        to.assertTerminated();</span>
<span class="nc" id="L175">        System.out.println(to.values());</span>
<span class="nc" id="L176">        to.assertValue(&quot;success&quot;);</span>
<span class="nc" id="L177">    }</span>

    /**
     * Test that we receive the onError if an exception is thrown from an operator that
     * does not have manual try/catch handling like map does.
     */
    @Test
    @Ignore(&quot;A crashing operator may leave the downstream in an inconsistent state and not suitable for event delivery&quot;)
    public void testOnErrorResumeReceivesErrorFromPreviousNonProtectedOperatorOnNext() {
<span class="nc" id="L186">        TestObserver&lt;String&gt; to = new TestObserver&lt;String&gt;();</span>
<span class="nc" id="L187">        Observable.just(1).lift(new ObservableOperator&lt;String, Integer&gt;() {</span>

            @Override
            public Observer&lt;? super Integer&gt; apply(final Observer&lt;? super String&gt; t1) {
<span class="nc" id="L191">                return new Observer&lt;Integer&gt;() {</span>

                    @Override
                    public void onSubscribe(Disposable d) {
<span class="nc" id="L195">                        t1.onSubscribe(d);</span>
<span class="nc" id="L196">                    }</span>

                    @Override
                    public void onComplete() {
<span class="nc" id="L200">                        throw new RuntimeException(&quot;failed&quot;);</span>
                    }

                    @Override
                    public void onError(Throwable e) {
<span class="nc" id="L205">                        throw new RuntimeException(&quot;failed&quot;);</span>
                    }

                    @Override
                    public void onNext(Integer t) {
<span class="nc" id="L210">                        throw new RuntimeException(&quot;failed&quot;);</span>
                    }

                };
            }

<span class="nc" id="L216">        }).onErrorResumeNext(new Function&lt;Throwable, Observable&lt;String&gt;&gt;() {</span>

            @Override
            public Observable&lt;String&gt; apply(Throwable t1) {
<span class="nc bnc" id="L220" title="All 2 branches missed.">                if (t1.getMessage().equals(&quot;failed&quot;)) {</span>
<span class="nc" id="L221">                    return Observable.just(&quot;success&quot;);</span>
                } else {
<span class="nc" id="L223">                    return Observable.error(t1);</span>
                }
            }

<span class="nc" id="L227">        }).subscribe(to);</span>

<span class="nc" id="L229">        to.assertTerminated();</span>
<span class="nc" id="L230">        System.out.println(to.values());</span>
<span class="nc" id="L231">        to.assertValue(&quot;success&quot;);</span>
<span class="nc" id="L232">    }</span>

    @Test
    public void testMapResumeAsyncNext() {
        // Trigger multiple failures
<span class="fc" id="L237">        Observable&lt;String&gt; w = Observable.just(&quot;one&quot;, &quot;fail&quot;, &quot;two&quot;, &quot;three&quot;, &quot;fail&quot;);</span>

        // Introduce map function that fails intermittently (Map does not prevent this when the Observer is a
        //  rx.operator incl onErrorResumeNextViaObservable)
<span class="fc" id="L241">        w = w.map(new Function&lt;String, String&gt;() {</span>
            @Override
            public String apply(String s) {
<span class="fc bfc" id="L244" title="All 2 branches covered.">                if (&quot;fail&quot;.equals(s)) {</span>
<span class="fc" id="L245">                    throw new RuntimeException(&quot;Forced Failure&quot;);</span>
                }
<span class="fc" id="L247">                System.out.println(&quot;BadMapper:&quot; + s);</span>
<span class="fc" id="L248">                return s;</span>
            }
        });

<span class="fc" id="L252">        Observable&lt;String&gt; o = w.onErrorResumeNext(new Function&lt;Throwable, Observable&lt;String&gt;&gt;() {</span>

            @Override
            public Observable&lt;String&gt; apply(Throwable t1) {
<span class="fc" id="L256">                return Observable.just(&quot;twoResume&quot;, &quot;threeResume&quot;).subscribeOn(Schedulers.computation());</span>
            }

        });

<span class="fc" id="L261">        Observer&lt;String&gt; observer = TestHelper.mockObserver();</span>

<span class="fc" id="L263">        TestObserver&lt;String&gt; to = new TestObserver&lt;String&gt;(observer);</span>
<span class="fc" id="L264">        o.subscribe(to);</span>
<span class="fc" id="L265">        to.awaitTerminalEvent();</span>

<span class="fc" id="L267">        verify(observer, Mockito.never()).onError(any(Throwable.class));</span>
<span class="fc" id="L268">        verify(observer, times(1)).onComplete();</span>
<span class="fc" id="L269">        verify(observer, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L270">        verify(observer, Mockito.never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L271">        verify(observer, Mockito.never()).onNext(&quot;three&quot;);</span>
<span class="fc" id="L272">        verify(observer, times(1)).onNext(&quot;twoResume&quot;);</span>
<span class="fc" id="L273">        verify(observer, times(1)).onNext(&quot;threeResume&quot;);</span>
<span class="fc" id="L274">    }</span>

    static class TestObservable implements ObservableSource&lt;String&gt; {

        final String[] values;
        Thread t;

<span class="fc" id="L281">        TestObservable(Subscription s, String... values) {</span>
<span class="fc" id="L282">            this.values = values;</span>
<span class="fc" id="L283">        }</span>

        @Override
        public void subscribe(final Observer&lt;? super String&gt; observer) {
<span class="fc" id="L287">            System.out.println(&quot;TestObservable subscribed to ...&quot;);</span>
<span class="fc" id="L288">            observer.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L289">            t = new Thread(new Runnable() {</span>

                @Override
                public void run() {
                    try {
<span class="fc" id="L294">                        System.out.println(&quot;running TestObservable thread&quot;);</span>
<span class="fc bfc" id="L295" title="All 2 branches covered.">                        for (String s : values) {</span>
<span class="fc" id="L296">                            System.out.println(&quot;TestObservable onNext: &quot; + s);</span>
<span class="fc" id="L297">                            observer.onNext(s);</span>
                        }
<span class="fc" id="L299">                        throw new RuntimeException(&quot;Forced Failure&quot;);</span>
<span class="fc" id="L300">                    } catch (Throwable e) {</span>
<span class="fc" id="L301">                        observer.onError(e);</span>
                    }
<span class="fc" id="L303">                }</span>

            });
<span class="fc" id="L306">            System.out.println(&quot;starting TestObservable thread&quot;);</span>
<span class="fc" id="L307">            t.start();</span>
<span class="fc" id="L308">            System.out.println(&quot;done starting TestObservable thread&quot;);</span>
<span class="fc" id="L309">        }</span>

    }

    @Test
    public void testBackpressure() {
<span class="fc" id="L315">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>
<span class="fc" id="L316">        Observable.range(0, 100000)</span>
<span class="fc" id="L317">                .onErrorResumeNext(new Function&lt;Throwable, Observable&lt;Integer&gt;&gt;() {</span>

                    @Override
                    public Observable&lt;Integer&gt; apply(Throwable t1) {
<span class="nc" id="L321">                        return Observable.just(1);</span>
                    }

                })
<span class="fc" id="L325">                .observeOn(Schedulers.computation())</span>
<span class="fc" id="L326">                .map(new Function&lt;Integer, Integer&gt;() {</span>
                    int c;

                    @Override
                    public Integer apply(Integer t1) {
<span class="fc bfc" id="L331" title="All 2 branches covered.">                        if (c++ &lt;= 1) {</span>
                            // slow
                            try {
<span class="fc" id="L334">                                Thread.sleep(500);</span>
<span class="nc" id="L335">                            } catch (InterruptedException e) {</span>
<span class="nc" id="L336">                                e.printStackTrace();</span>
<span class="fc" id="L337">                            }</span>
                        }
<span class="fc" id="L339">                        return t1;</span>
                    }

                })
<span class="fc" id="L343">                .subscribe(to);</span>
<span class="fc" id="L344">        to.awaitTerminalEvent();</span>
<span class="fc" id="L345">        to.assertNoErrors();</span>
<span class="fc" id="L346">    }</span>

    @Test
    public void badOtherSource() {
<span class="fc" id="L350">        TestHelper.checkBadSourceObservable(new Function&lt;Observable&lt;Integer&gt;, Object&gt;() {</span>
            @Override
            public Object apply(Observable&lt;Integer&gt; o) throws Exception {
<span class="fc" id="L353">                return Observable.error(new IOException())</span>
<span class="fc" id="L354">                        .onErrorResumeNext(Functions.justFunction(o));</span>
            }
<span class="fc" id="L356">        }, false, 1, 1, 1);</span>
<span class="fc" id="L357">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>