<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>ObservableOnErrorReturnTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.operators.observable</a> &gt; <span class="el_source">ObservableOnErrorReturnTest.java</span></div><h1>ObservableOnErrorReturnTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.operators.observable;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

import java.util.concurrent.atomic.AtomicReference;

import org.junit.Test;
import org.mockito.Mockito;

import io.reactivex.*;
import io.reactivex.disposables.Disposables;
import io.reactivex.exceptions.TestException;
import io.reactivex.functions.Function;
import io.reactivex.observers.*;
import io.reactivex.schedulers.Schedulers;

<span class="fc" id="L31">public class ObservableOnErrorReturnTest {</span>

    @Test
    public void testResumeNext() {
<span class="fc" id="L35">        TestObservable f = new TestObservable(&quot;one&quot;);</span>
<span class="fc" id="L36">        Observable&lt;String&gt; w = Observable.unsafeCreate(f);</span>
<span class="fc" id="L37">        final AtomicReference&lt;Throwable&gt; capturedException = new AtomicReference&lt;Throwable&gt;();</span>

<span class="fc" id="L39">        Observable&lt;String&gt; observable = w.onErrorReturn(new Function&lt;Throwable, String&gt;() {</span>

            @Override
            public String apply(Throwable e) {
<span class="fc" id="L43">                capturedException.set(e);</span>
<span class="fc" id="L44">                return &quot;failure&quot;;</span>
            }

        });

<span class="fc" id="L49">        Observer&lt;String&gt; observer = TestHelper.mockObserver();</span>
<span class="fc" id="L50">        observable.subscribe(observer);</span>

        try {
<span class="fc" id="L53">            f.t.join();</span>
<span class="nc" id="L54">        } catch (InterruptedException e) {</span>
<span class="nc" id="L55">            fail(e.getMessage());</span>
<span class="fc" id="L56">        }</span>

<span class="fc" id="L58">        verify(observer, Mockito.never()).onError(any(Throwable.class));</span>
<span class="fc" id="L59">        verify(observer, times(1)).onComplete();</span>
<span class="fc" id="L60">        verify(observer, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L61">        verify(observer, times(1)).onNext(&quot;failure&quot;);</span>
<span class="fc" id="L62">        assertNotNull(capturedException.get());</span>
<span class="fc" id="L63">    }</span>

    /**
     * Test that when a function throws an exception this is propagated through onError.
     */
    @Test
    public void testFunctionThrowsError() {
<span class="fc" id="L70">        TestObservable f = new TestObservable(&quot;one&quot;);</span>
<span class="fc" id="L71">        Observable&lt;String&gt; w = Observable.unsafeCreate(f);</span>
<span class="fc" id="L72">        final AtomicReference&lt;Throwable&gt; capturedException = new AtomicReference&lt;Throwable&gt;();</span>

<span class="fc" id="L74">        Observable&lt;String&gt; observable = w.onErrorReturn(new Function&lt;Throwable, String&gt;() {</span>

            @Override
            public String apply(Throwable e) {
<span class="fc" id="L78">                capturedException.set(e);</span>
<span class="fc" id="L79">                throw new RuntimeException(&quot;exception from function&quot;);</span>
            }

        });

<span class="fc" id="L84">        Observer&lt;String&gt; observer = TestHelper.mockObserver();</span>
<span class="fc" id="L85">        observable.subscribe(observer);</span>

        try {
<span class="fc" id="L88">            f.t.join();</span>
<span class="nc" id="L89">        } catch (InterruptedException e) {</span>
<span class="nc" id="L90">            fail(e.getMessage());</span>
<span class="fc" id="L91">        }</span>

        // we should get the &quot;one&quot; value before the error
<span class="fc" id="L94">        verify(observer, times(1)).onNext(&quot;one&quot;);</span>

        // we should have received an onError call on the Observer since the resume function threw an exception
<span class="fc" id="L97">        verify(observer, times(1)).onError(any(Throwable.class));</span>
<span class="fc" id="L98">        verify(observer, times(0)).onComplete();</span>
<span class="fc" id="L99">        assertNotNull(capturedException.get());</span>
<span class="fc" id="L100">    }</span>

    @Test
    public void testMapResumeAsyncNext() {
        // Trigger multiple failures
<span class="fc" id="L105">        Observable&lt;String&gt; w = Observable.just(&quot;one&quot;, &quot;fail&quot;, &quot;two&quot;, &quot;three&quot;, &quot;fail&quot;);</span>

        // Introduce map function that fails intermittently (Map does not prevent this when the Observer is a
        //  rx.operator incl onErrorResumeNextViaObservable)
<span class="fc" id="L109">        w = w.map(new Function&lt;String, String&gt;() {</span>
            @Override
            public String apply(String s) {
<span class="fc bfc" id="L112" title="All 2 branches covered.">                if (&quot;fail&quot;.equals(s)) {</span>
<span class="fc" id="L113">                    throw new RuntimeException(&quot;Forced Failure&quot;);</span>
                }
<span class="fc" id="L115">                System.out.println(&quot;BadMapper:&quot; + s);</span>
<span class="fc" id="L116">                return s;</span>
            }
        });

<span class="fc" id="L120">        Observable&lt;String&gt; observable = w.onErrorReturn(new Function&lt;Throwable, String&gt;() {</span>

            @Override
            public String apply(Throwable t1) {
<span class="fc" id="L124">                return &quot;resume&quot;;</span>
            }

        });

<span class="fc" id="L129">        Observer&lt;String&gt; observer = TestHelper.mockObserver();</span>
<span class="fc" id="L130">        TestObserver&lt;String&gt; to = new TestObserver&lt;String&gt;(observer);</span>
<span class="fc" id="L131">        observable.subscribe(to);</span>
<span class="fc" id="L132">        to.awaitTerminalEvent();</span>

<span class="fc" id="L134">        verify(observer, Mockito.never()).onError(any(Throwable.class));</span>
<span class="fc" id="L135">        verify(observer, times(1)).onComplete();</span>
<span class="fc" id="L136">        verify(observer, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L137">        verify(observer, Mockito.never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L138">        verify(observer, Mockito.never()).onNext(&quot;three&quot;);</span>
<span class="fc" id="L139">        verify(observer, times(1)).onNext(&quot;resume&quot;);</span>
<span class="fc" id="L140">    }</span>

    @Test
    public void testBackpressure() {
<span class="fc" id="L144">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>
<span class="fc" id="L145">        Observable.range(0, 100000)</span>
<span class="fc" id="L146">                .onErrorReturn(new Function&lt;Throwable, Integer&gt;() {</span>

                    @Override
                    public Integer apply(Throwable t1) {
<span class="nc" id="L150">                        return 1;</span>
                    }

                })
<span class="fc" id="L154">                .observeOn(Schedulers.computation())</span>
<span class="fc" id="L155">                .map(new Function&lt;Integer, Integer&gt;() {</span>
                    int c;

                    @Override
                    public Integer apply(Integer t1) {
<span class="fc bfc" id="L160" title="All 2 branches covered.">                        if (c++ &lt;= 1) {</span>
                            // slow
                            try {
<span class="fc" id="L163">                                Thread.sleep(500);</span>
<span class="nc" id="L164">                            } catch (InterruptedException e) {</span>
<span class="nc" id="L165">                                e.printStackTrace();</span>
<span class="fc" id="L166">                            }</span>
                        }
<span class="fc" id="L168">                        return t1;</span>
                    }

                })
<span class="fc" id="L172">                .subscribe(to);</span>
<span class="fc" id="L173">        to.awaitTerminalEvent();</span>
<span class="fc" id="L174">        to.assertNoErrors();</span>
<span class="fc" id="L175">    }</span>

    private static class TestObservable implements ObservableSource&lt;String&gt; {

        final String[] values;
        Thread t;

<span class="fc" id="L182">        TestObservable(String... values) {</span>
<span class="fc" id="L183">            this.values = values;</span>
<span class="fc" id="L184">        }</span>

        @Override
        public void subscribe(final Observer&lt;? super String&gt; observer) {
<span class="fc" id="L188">            observer.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L189">            System.out.println(&quot;TestObservable subscribed to ...&quot;);</span>
<span class="fc" id="L190">            t = new Thread(new Runnable() {</span>

                @Override
                public void run() {
                    try {
<span class="fc" id="L195">                        System.out.println(&quot;running TestObservable thread&quot;);</span>
<span class="fc bfc" id="L196" title="All 2 branches covered.">                        for (String s : values) {</span>
<span class="fc" id="L197">                            System.out.println(&quot;TestObservable onNext: &quot; + s);</span>
<span class="fc" id="L198">                            observer.onNext(s);</span>
                        }
<span class="fc" id="L200">                        throw new RuntimeException(&quot;Forced Failure&quot;);</span>
<span class="fc" id="L201">                    } catch (Throwable e) {</span>
<span class="fc" id="L202">                        observer.onError(e);</span>
                    }
<span class="fc" id="L204">                }</span>

            });
<span class="fc" id="L207">            System.out.println(&quot;starting TestObservable thread&quot;);</span>
<span class="fc" id="L208">            t.start();</span>
<span class="fc" id="L209">            System.out.println(&quot;done starting TestObservable thread&quot;);</span>
<span class="fc" id="L210">        }</span>
    }

    @Test
    public void returnItem() {
<span class="fc" id="L215">        Observable.error(new TestException())</span>
<span class="fc" id="L216">        .onErrorReturnItem(1)</span>
<span class="fc" id="L217">        .test()</span>
<span class="fc" id="L218">        .assertResult(1);</span>
<span class="fc" id="L219">    }</span>

    @Test
    public void dispose() {
<span class="fc" id="L223">        TestHelper.checkDisposed(Observable.just(1).onErrorReturnItem(1));</span>
<span class="fc" id="L224">    }</span>

    @Test
    public void doubleOnSubscribe() {
<span class="fc" id="L228">        TestHelper.checkDoubleOnSubscribeObservable(new Function&lt;Observable&lt;Object&gt;, ObservableSource&lt;Object&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;Object&gt; apply(Observable&lt;Object&gt; f) throws Exception {
<span class="fc" id="L231">                return f.onErrorReturnItem(1);</span>
            }
        });
<span class="fc" id="L234">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>