<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>TestObserverTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.observers</a> &gt; <span class="el_source">TestObserverTest.java</span></div><h1>TestObserverTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.observers;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.TimeUnit;

import org.junit.*;
import org.junit.rules.ExpectedException;
import org.mockito.InOrder;
import org.reactivestreams.Subscriber;

import io.reactivex.*;
import io.reactivex.Observable;
import io.reactivex.Observer;
import io.reactivex.disposables.*;
import io.reactivex.exceptions.TestException;
import io.reactivex.functions.*;
import io.reactivex.internal.functions.Functions;
import io.reactivex.internal.fuseable.*;
import io.reactivex.internal.operators.observable.ObservableScalarXMap.ScalarDisposable;
import io.reactivex.internal.subscriptions.EmptySubscription;
import io.reactivex.processors.PublishProcessor;
import io.reactivex.schedulers.Schedulers;
import io.reactivex.subjects.UnicastSubject;
import io.reactivex.subscribers.TestSubscriber;

<span class="fc" id="L43">public class TestObserverTest {</span>

<span class="fc" id="L45">    @Rule</span>
<span class="fc" id="L46">    public ExpectedException thrown = ExpectedException.none();</span>

    @Test
    public void testAssert() {
<span class="fc" id="L50">        Flowable&lt;Integer&gt; oi = Flowable.fromIterable(Arrays.asList(1, 2));</span>
<span class="fc" id="L51">        TestSubscriber&lt;Integer&gt; subscriber = new TestSubscriber&lt;Integer&gt;();</span>
<span class="fc" id="L52">        oi.subscribe(subscriber);</span>

<span class="fc" id="L54">        subscriber.assertValues(1, 2);</span>
<span class="fc" id="L55">        subscriber.assertValueCount(2);</span>
<span class="fc" id="L56">        subscriber.assertTerminated();</span>
<span class="fc" id="L57">    }</span>

    @Test
    public void testAssertNotMatchCount() {
<span class="fc" id="L61">        Flowable&lt;Integer&gt; oi = Flowable.fromIterable(Arrays.asList(1, 2));</span>
<span class="fc" id="L62">        TestSubscriber&lt;Integer&gt; subscriber = new TestSubscriber&lt;Integer&gt;();</span>
<span class="fc" id="L63">        oi.subscribe(subscriber);</span>

<span class="fc" id="L65">        thrown.expect(AssertionError.class);</span>
        // FIXME different message format
//        thrown.expectMessage(&quot;Number of items does not match. Provided: 1  Actual: 2&quot;);

<span class="nc" id="L69">        subscriber.assertValue(1);</span>
<span class="nc" id="L70">        subscriber.assertValueCount(2);</span>
<span class="nc" id="L71">        subscriber.assertTerminated();</span>
<span class="nc" id="L72">    }</span>

    @Test
    public void testAssertNotMatchValue() {
<span class="fc" id="L76">        Flowable&lt;Integer&gt; oi = Flowable.fromIterable(Arrays.asList(1, 2));</span>
<span class="fc" id="L77">        TestSubscriber&lt;Integer&gt; subscriber = new TestSubscriber&lt;Integer&gt;();</span>
<span class="fc" id="L78">        oi.subscribe(subscriber);</span>

<span class="fc" id="L80">        thrown.expect(AssertionError.class);</span>
        // FIXME different message format
//        thrown.expectMessage(&quot;Value at index: 1 expected to be [3] (Integer) but was: [2] (Integer)&quot;);

<span class="nc" id="L84">        subscriber.assertValues(1, 3);</span>
<span class="nc" id="L85">        subscriber.assertValueCount(2);</span>
<span class="nc" id="L86">        subscriber.assertTerminated();</span>
<span class="nc" id="L87">    }</span>

    @Test
    public void assertNeverAtNotMatchingValue() {
<span class="fc" id="L91">        Flowable&lt;Integer&gt; oi = Flowable.fromIterable(Arrays.asList(1, 2));</span>
<span class="fc" id="L92">        TestSubscriber&lt;Integer&gt; subscriber = new TestSubscriber&lt;Integer&gt;();</span>
<span class="fc" id="L93">        oi.subscribe(subscriber);</span>

<span class="fc" id="L95">        subscriber.assertNever(3);</span>
<span class="fc" id="L96">        subscriber.assertValueCount(2);</span>
<span class="fc" id="L97">        subscriber.assertTerminated();</span>
<span class="fc" id="L98">    }</span>

    @Test
    public void assertNeverAtMatchingValue() {
<span class="fc" id="L102">        Flowable&lt;Integer&gt; oi = Flowable.fromIterable(Arrays.asList(1, 2));</span>
<span class="fc" id="L103">        TestSubscriber&lt;Integer&gt; subscriber = new TestSubscriber&lt;Integer&gt;();</span>
<span class="fc" id="L104">        oi.subscribe(subscriber);</span>

<span class="fc" id="L106">        subscriber.assertValues(1, 2);</span>

<span class="fc" id="L108">        thrown.expect(AssertionError.class);</span>

<span class="nc" id="L110">        subscriber.assertNever(2);</span>
<span class="nc" id="L111">        subscriber.assertValueCount(2);</span>
<span class="nc" id="L112">        subscriber.assertTerminated();</span>
<span class="nc" id="L113">    }</span>

    @Test
    public void assertNeverAtMatchingPredicate() {
<span class="fc" id="L117">        TestSubscriber&lt;Integer&gt; ts = new TestSubscriber&lt;Integer&gt;();</span>

<span class="fc" id="L119">        Flowable.just(1, 2).subscribe(ts);</span>

<span class="fc" id="L121">        ts.assertValues(1, 2);</span>

<span class="fc" id="L123">        thrown.expect(AssertionError.class);</span>

<span class="pc" id="L125">        ts.assertNever(new Predicate&lt;Integer&gt;() {</span>
            @Override
            public boolean test(final Integer o) throws Exception {
<span class="pc bpc" id="L128" title="1 of 2 branches missed.">                return o == 1;</span>
            }
        });
<span class="nc" id="L131">    }</span>

    @Test
    public void assertNeverAtNotMatchingPredicate() {
<span class="fc" id="L135">        TestSubscriber&lt;Integer&gt; ts = new TestSubscriber&lt;Integer&gt;();</span>

<span class="fc" id="L137">        Flowable.just(2, 3).subscribe(ts);</span>

<span class="fc" id="L139">        ts.assertNever(new Predicate&lt;Integer&gt;() {</span>
            @Override
            public boolean test(final Integer o) throws Exception {
<span class="pc bpc" id="L142" title="1 of 2 branches missed.">                return o == 1;</span>
            }
        });
<span class="fc" id="L145">    }</span>

    @Test
    public void testAssertTerminalEventNotReceived() {
<span class="fc" id="L149">        PublishProcessor&lt;Integer&gt; p = PublishProcessor.create();</span>
<span class="fc" id="L150">        TestSubscriber&lt;Integer&gt; subscriber = new TestSubscriber&lt;Integer&gt;();</span>
<span class="fc" id="L151">        p.subscribe(subscriber);</span>

<span class="fc" id="L153">        p.onNext(1);</span>
<span class="fc" id="L154">        p.onNext(2);</span>

<span class="fc" id="L156">        thrown.expect(AssertionError.class);</span>
        // FIXME different message format
//        thrown.expectMessage(&quot;No terminal events received.&quot;);

<span class="fc" id="L160">        subscriber.assertValues(1, 2);</span>
<span class="fc" id="L161">        subscriber.assertValueCount(2);</span>
<span class="nc" id="L162">        subscriber.assertTerminated();</span>
<span class="nc" id="L163">    }</span>

    @Test
    public void testWrappingMock() {
<span class="fc" id="L167">        Flowable&lt;Integer&gt; oi = Flowable.fromIterable(Arrays.asList(1, 2));</span>

<span class="fc" id="L169">        Subscriber&lt;Integer&gt; mockSubscriber = TestHelper.mockSubscriber();</span>

<span class="fc" id="L171">        oi.subscribe(new TestSubscriber&lt;Integer&gt;(mockSubscriber));</span>

<span class="fc" id="L173">        InOrder inOrder = inOrder(mockSubscriber);</span>
<span class="fc" id="L174">        inOrder.verify(mockSubscriber, times(1)).onNext(1);</span>
<span class="fc" id="L175">        inOrder.verify(mockSubscriber, times(1)).onNext(2);</span>
<span class="fc" id="L176">        inOrder.verify(mockSubscriber, times(1)).onComplete();</span>
<span class="fc" id="L177">        inOrder.verifyNoMoreInteractions();</span>
<span class="fc" id="L178">    }</span>

    @Test
    public void testWrappingMockWhenUnsubscribeInvolved() {
<span class="fc" id="L182">        Flowable&lt;Integer&gt; oi = Flowable.fromIterable(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9)).take(2);</span>
<span class="fc" id="L183">        Subscriber&lt;Integer&gt; mockSubscriber = TestHelper.mockSubscriber();</span>
<span class="fc" id="L184">        oi.subscribe(new TestSubscriber&lt;Integer&gt;(mockSubscriber));</span>

<span class="fc" id="L186">        InOrder inOrder = inOrder(mockSubscriber);</span>
<span class="fc" id="L187">        inOrder.verify(mockSubscriber, times(1)).onNext(1);</span>
<span class="fc" id="L188">        inOrder.verify(mockSubscriber, times(1)).onNext(2);</span>
<span class="fc" id="L189">        inOrder.verify(mockSubscriber, times(1)).onComplete();</span>
<span class="fc" id="L190">        inOrder.verifyNoMoreInteractions();</span>
<span class="fc" id="L191">    }</span>

    @Test
    public void testErrorSwallowed() {
<span class="fc" id="L195">        Flowable.error(new RuntimeException()).subscribe(new TestSubscriber&lt;Object&gt;());</span>
<span class="fc" id="L196">    }</span>

    @Test
    public void testGetEvents() {
<span class="fc" id="L200">        TestSubscriber&lt;Integer&gt; ts = new TestSubscriber&lt;Integer&gt;();</span>
<span class="fc" id="L201">        ts.onSubscribe(EmptySubscription.INSTANCE);</span>
<span class="fc" id="L202">        ts.onNext(1);</span>
<span class="fc" id="L203">        ts.onNext(2);</span>

<span class="fc" id="L205">        assertEquals(Arrays.&lt;Object&gt;asList(Arrays.asList(1, 2),</span>
<span class="fc" id="L206">                Collections.emptyList(),</span>
<span class="fc" id="L207">                Collections.emptyList()), ts.getEvents());</span>

<span class="fc" id="L209">        ts.onComplete();</span>

<span class="fc" id="L211">        assertEquals(Arrays.&lt;Object&gt;asList(Arrays.asList(1, 2), Collections.emptyList(),</span>
<span class="fc" id="L212">                Collections.singletonList(Notification.createOnComplete())), ts.getEvents());</span>

<span class="fc" id="L214">        TestException ex = new TestException();</span>
<span class="fc" id="L215">        TestSubscriber&lt;Integer&gt; ts2 = new TestSubscriber&lt;Integer&gt;();</span>
<span class="fc" id="L216">        ts2.onSubscribe(EmptySubscription.INSTANCE);</span>
<span class="fc" id="L217">        ts2.onNext(1);</span>
<span class="fc" id="L218">        ts2.onNext(2);</span>

<span class="fc" id="L220">        assertEquals(Arrays.&lt;Object&gt;asList(Arrays.asList(1, 2),</span>
<span class="fc" id="L221">                Collections.emptyList(),</span>
<span class="fc" id="L222">                Collections.emptyList()), ts2.getEvents());</span>

<span class="fc" id="L224">        ts2.onError(ex);</span>

<span class="fc" id="L226">        assertEquals(Arrays.&lt;Object&gt;asList(</span>
<span class="fc" id="L227">                Arrays.asList(1, 2),</span>
<span class="fc" id="L228">                Collections.singletonList(ex),</span>
<span class="fc" id="L229">                Collections.emptyList()),</span>
<span class="fc" id="L230">                    ts2.getEvents());</span>
<span class="fc" id="L231">    }</span>

    @Test
    public void testNullExpected() {
<span class="fc" id="L235">        TestSubscriber&lt;Integer&gt; ts = new TestSubscriber&lt;Integer&gt;();</span>
<span class="fc" id="L236">        ts.onNext(1);</span>

        try {
<span class="nc" id="L239">            ts.assertValue((Integer) null);</span>
<span class="fc" id="L240">        } catch (AssertionError ex) {</span>
            // this is expected
<span class="fc" id="L242">            return;</span>
<span class="nc" id="L243">        }</span>
<span class="nc" id="L244">        fail(&quot;Null element check assertion didn't happen!&quot;);</span>
<span class="nc" id="L245">    }</span>

    @Test
    public void testNullActual() {
<span class="fc" id="L249">        TestSubscriber&lt;Integer&gt; ts = new TestSubscriber&lt;Integer&gt;();</span>
<span class="fc" id="L250">        ts.onNext(null);</span>

        try {
<span class="nc" id="L253">            ts.assertValue(1);</span>
<span class="fc" id="L254">        } catch (AssertionError ex) {</span>
            // this is expected
<span class="fc" id="L256">            return;</span>
<span class="nc" id="L257">        }</span>
<span class="nc" id="L258">        fail(&quot;Null element check assertion didn't happen!&quot;);</span>
<span class="nc" id="L259">    }</span>

    @Test
    public void testTerminalErrorOnce() {
<span class="fc" id="L263">        TestSubscriber&lt;Integer&gt; ts = new TestSubscriber&lt;Integer&gt;();</span>
<span class="fc" id="L264">        ts.onError(new TestException());</span>
<span class="fc" id="L265">        ts.onError(new TestException());</span>

        try {
<span class="nc" id="L268">            ts.assertTerminated();</span>
<span class="fc" id="L269">        } catch (AssertionError ex) {</span>
            // this is expected
<span class="fc" id="L271">            return;</span>
<span class="nc" id="L272">        }</span>
<span class="nc" id="L273">        fail(&quot;Failed to report multiple onError terminal events!&quot;);</span>
<span class="nc" id="L274">    }</span>

    @Test
    public void testTerminalCompletedOnce() {
<span class="fc" id="L278">        TestSubscriber&lt;Integer&gt; ts = new TestSubscriber&lt;Integer&gt;();</span>
<span class="fc" id="L279">        ts.onComplete();</span>
<span class="fc" id="L280">        ts.onComplete();</span>

        try {
<span class="nc" id="L283">            ts.assertTerminated();</span>
<span class="fc" id="L284">        } catch (AssertionError ex) {</span>
            // this is expected
<span class="fc" id="L286">            return;</span>
<span class="nc" id="L287">        }</span>
<span class="nc" id="L288">        fail(&quot;Failed to report multiple onComplete terminal events!&quot;);</span>
<span class="nc" id="L289">    }</span>

    @Test
    public void testTerminalOneKind() {
<span class="fc" id="L293">        TestSubscriber&lt;Integer&gt; ts = new TestSubscriber&lt;Integer&gt;();</span>
<span class="fc" id="L294">        ts.onError(new TestException());</span>
<span class="fc" id="L295">        ts.onComplete();</span>

        try {
<span class="nc" id="L298">            ts.assertTerminated();</span>
<span class="fc" id="L299">        } catch (AssertionError ex) {</span>
            // this is expected
<span class="fc" id="L301">            return;</span>
<span class="nc" id="L302">        }</span>
<span class="nc" id="L303">        fail(&quot;Failed to report multiple kinds of events!&quot;);</span>
<span class="nc" id="L304">    }</span>

    @Test
    public void createDelegate() {
<span class="fc" id="L308">        TestObserver&lt;Integer&gt; to1 = TestObserver.create();</span>

<span class="fc" id="L310">        TestObserver&lt;Integer&gt; to = TestObserver.create(to1);</span>

<span class="fc" id="L312">        to.assertNotSubscribed();</span>

<span class="fc" id="L314">        assertFalse(to.hasSubscription());</span>

<span class="fc" id="L316">        to.onSubscribe(Disposables.empty());</span>

        try {
<span class="nc" id="L319">            to.assertNotSubscribed();</span>
<span class="nc" id="L320">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L321">        } catch (AssertionError ex) {</span>
            // expected
        }

<span class="fc" id="L325">        assertTrue(to.hasSubscription());</span>

<span class="fc" id="L327">        assertFalse(to.isDisposed());</span>

<span class="fc" id="L329">        to.onNext(1);</span>
<span class="fc" id="L330">        to.onError(new TestException());</span>
<span class="fc" id="L331">        to.onComplete();</span>

<span class="fc" id="L333">        to1.assertValue(1).assertError(TestException.class).assertComplete();</span>

<span class="fc" id="L335">        to.dispose();</span>

<span class="fc" id="L337">        assertTrue(to.isDisposed());</span>

<span class="fc" id="L339">        assertTrue(to.isTerminated());</span>

<span class="fc" id="L341">        assertSame(Thread.currentThread(), to.lastThread());</span>

        try {
<span class="nc" id="L344">            to.assertNoValues();</span>
<span class="nc" id="L345">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L346">        } catch (AssertionError exc) {</span>
            // expected
        }

        try {
<span class="nc" id="L351">            to.assertValueCount(0);</span>
<span class="nc" id="L352">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L353">        } catch (AssertionError exc) {</span>
            // expected
        }

<span class="fc" id="L357">        to.assertValueSequence(Collections.singletonList(1));</span>

        try {
<span class="nc" id="L360">            to.assertValueSequence(Collections.singletonList(2));</span>
<span class="nc" id="L361">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L362">        } catch (AssertionError exc) {</span>
            // expected
        }

<span class="fc" id="L366">        to.assertValueSet(Collections.singleton(1));</span>

        try {
<span class="nc" id="L369">            to.assertValueSet(Collections.singleton(2));</span>
<span class="nc" id="L370">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L371">        } catch (AssertionError exc) {</span>
            // expected
        }

<span class="fc" id="L375">    }</span>

    @Test
    public void assertError() {
<span class="fc" id="L379">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>

        try {
<span class="nc" id="L382">            to.assertError(TestException.class);</span>
<span class="nc" id="L383">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L384">        } catch (AssertionError ex) {</span>
            // expected
        }

        try {
<span class="nc" id="L389">            to.assertError(new TestException());</span>
<span class="nc" id="L390">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L391">        } catch (AssertionError ex) {</span>
            // expected
        }

        try {
<span class="nc" id="L396">            to.assertError(Functions.&lt;Throwable&gt;alwaysTrue());</span>
<span class="nc" id="L397">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L398">        } catch (AssertionError ex) {</span>
            // expected
        }

        try {
<span class="nc" id="L403">            to.assertErrorMessage(&quot;&quot;);</span>
<span class="nc" id="L404">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L405">        } catch (AssertionError exc) {</span>
            // expected
        }

        try {
<span class="nc" id="L410">            to.assertSubscribed();</span>
<span class="nc" id="L411">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L412">        } catch (AssertionError exc) {</span>
            // expected
        }

        try {
<span class="nc" id="L417">            to.assertTerminated();</span>
<span class="nc" id="L418">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L419">        } catch (AssertionError exc) {</span>
            // expected
        }

<span class="fc" id="L423">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L425">        to.assertSubscribed();</span>

<span class="fc" id="L427">        to.assertNoErrors();</span>

<span class="fc" id="L429">        TestException ex = new TestException(&quot;Forced failure&quot;);</span>

<span class="fc" id="L431">        to.onError(ex);</span>

<span class="fc" id="L433">        to.assertError(ex);</span>

<span class="fc" id="L435">        to.assertError(TestException.class);</span>

<span class="fc" id="L437">        to.assertError(Functions.&lt;Throwable&gt;alwaysTrue());</span>

<span class="fc" id="L439">        to.assertError(new Predicate&lt;Throwable&gt;() {</span>
            @Override
            public boolean test(Throwable t) throws Exception {
<span class="pc bpc" id="L442" title="2 of 4 branches missed.">                return t.getMessage() != null &amp;&amp; t.getMessage().contains(&quot;Forced&quot;);</span>
            }
        });

<span class="fc" id="L446">        to.assertErrorMessage(&quot;Forced failure&quot;);</span>

        try {
<span class="nc" id="L449">            to.assertErrorMessage(&quot;&quot;);</span>
<span class="nc" id="L450">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L451">        } catch (AssertionError exc) {</span>
            // expected
        }

        try {
<span class="nc" id="L456">            to.assertError(new RuntimeException());</span>
<span class="nc" id="L457">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L458">        } catch (AssertionError exc) {</span>
            // expected
        }

        try {
<span class="nc" id="L463">            to.assertError(IOException.class);</span>
<span class="nc" id="L464">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L465">        } catch (AssertionError exc) {</span>
            // expected
        }

        try {
<span class="nc" id="L470">            to.assertError(Functions.&lt;Throwable&gt;alwaysFalse());</span>
<span class="nc" id="L471">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L472">        } catch (AssertionError exc) {</span>
            // expected
        }

        try {
<span class="nc" id="L477">            to.assertNoErrors();</span>
<span class="nc" id="L478">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L479">        } catch (AssertionError exc) {</span>
            // expected
        }

<span class="fc" id="L483">        to.assertTerminated();</span>

<span class="fc" id="L485">        to.assertValueCount(0);</span>

<span class="fc" id="L487">        to.assertNoValues();</span>
<span class="fc" id="L488">    }</span>

    @Test
    public void emptyObserverEnum() {
<span class="fc" id="L492">        assertEquals(1, TestObserver.EmptyObserver.values().length);</span>
<span class="fc" id="L493">        assertNotNull(TestObserver.EmptyObserver.valueOf(&quot;INSTANCE&quot;));</span>
<span class="fc" id="L494">    }</span>

    @Test
    public void valueAndClass() {
<span class="fc" id="L498">        assertEquals(&quot;null&quot;, TestObserver.valueAndClass(null));</span>
<span class="fc" id="L499">        assertEquals(&quot;1 (class: Integer)&quot;, TestObserver.valueAndClass(1));</span>
<span class="fc" id="L500">    }</span>

    @Test
    public void assertFailure() {
<span class="fc" id="L504">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>

<span class="fc" id="L506">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L508">        to.onError(new TestException(&quot;Forced failure&quot;));</span>

<span class="fc" id="L510">        to.assertFailure(TestException.class);</span>

<span class="fc" id="L512">        to.assertFailure(Functions.&lt;Throwable&gt;alwaysTrue());</span>

<span class="fc" id="L514">        to.assertFailureAndMessage(TestException.class, &quot;Forced failure&quot;);</span>

<span class="fc" id="L516">        to.onNext(1);</span>

<span class="fc" id="L518">        to.assertFailure(TestException.class, 1);</span>

<span class="fc" id="L520">        to.assertFailure(Functions.&lt;Throwable&gt;alwaysTrue(), 1);</span>

<span class="fc" id="L522">        to.assertFailureAndMessage(TestException.class, &quot;Forced failure&quot;, 1);</span>
<span class="fc" id="L523">    }</span>

    @Test
    public void assertFuseable() {
<span class="fc" id="L527">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>

<span class="fc" id="L529">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L531">        to.assertNotFuseable();</span>

        try {
<span class="nc" id="L534">            to.assertFuseable();</span>
<span class="nc" id="L535">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L536">        } catch (AssertionError ex) {</span>
            // expected
        }

        try {
<span class="nc" id="L541">            to.assertFusionMode(QueueFuseable.SYNC);</span>
<span class="nc" id="L542">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L543">        } catch (AssertionError ex) {</span>
            // expected
        }

<span class="fc" id="L547">        to = TestObserver.create();</span>
<span class="fc" id="L548">        to.setInitialFusionMode(QueueFuseable.ANY);</span>

<span class="fc" id="L550">        to.onSubscribe(new ScalarDisposable&lt;Integer&gt;(to, 1));</span>

<span class="fc" id="L552">        to.assertFuseable();</span>

<span class="fc" id="L554">        to.assertFusionMode(QueueFuseable.SYNC);</span>

        try {
<span class="nc" id="L557">            to.assertFusionMode(QueueFuseable.NONE);</span>
<span class="nc" id="L558">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L559">        } catch (AssertionError ex) {</span>
            // expected
        }

        try {
<span class="nc" id="L564">            to.assertNotFuseable();</span>
<span class="nc" id="L565">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L566">        } catch (AssertionError ex) {</span>
            // expected
        }

<span class="fc" id="L570">    }</span>

    @Test
    public void assertTerminated() {
<span class="fc" id="L574">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>

<span class="fc" id="L576">        to.assertNotTerminated();</span>

<span class="fc" id="L578">        to.onError(null);</span>

        try {
<span class="nc" id="L581">            to.assertNotTerminated();</span>
<span class="nc" id="L582">            throw new RuntimeException(&quot;Should have thrown!&quot;);</span>
<span class="fc" id="L583">        } catch (AssertionError ex) {</span>
            // expected
        }
<span class="fc" id="L586">    }</span>

    @Test
    public void assertOf() {
<span class="fc" id="L590">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>

<span class="fc" id="L592">        to.assertOf(new Consumer&lt;TestObserver&lt;Integer&gt;&gt;() {</span>
            @Override
            public void accept(TestObserver&lt;Integer&gt; f) throws Exception {
<span class="fc" id="L595">                f.assertNotSubscribed();</span>
<span class="fc" id="L596">            }</span>
        });

        try {
<span class="pc" id="L600">            to.assertOf(new Consumer&lt;TestObserver&lt;Integer&gt;&gt;() {</span>
                @Override
                public void accept(TestObserver&lt;Integer&gt; f) throws Exception {
<span class="nc" id="L603">                    f.assertSubscribed();</span>
<span class="nc" id="L604">                }</span>
            });
<span class="nc" id="L606">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L607">        } catch (AssertionError ex) {</span>
            // expected
        }

        try {
<span class="pc" id="L612">            to.assertOf(new Consumer&lt;TestObserver&lt;Integer&gt;&gt;() {</span>
                @Override
                public void accept(TestObserver&lt;Integer&gt; f) throws Exception {
<span class="fc" id="L615">                    throw new IllegalArgumentException();</span>
                }
            });
<span class="nc" id="L618">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L619">        } catch (IllegalArgumentException ex) {</span>
            // expected
        }
<span class="fc" id="L622">    }</span>

    @Test
    public void assertResult() {
<span class="fc" id="L626">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>

<span class="fc" id="L628">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L630">        to.onComplete();</span>

<span class="fc" id="L632">        to.assertResult();</span>

        try {
<span class="nc" id="L635">            to.assertResult(1);</span>
<span class="nc" id="L636">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L637">        } catch (AssertionError ex) {</span>
            // expected
        }

<span class="fc" id="L641">        to.onNext(1);</span>

<span class="fc" id="L643">        to.assertResult(1);</span>

        try {
<span class="nc" id="L646">            to.assertResult(2);</span>
<span class="nc" id="L647">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L648">        } catch (AssertionError ex) {</span>
            // expected
        }

        try {
<span class="nc" id="L653">            to.assertResult();</span>
<span class="nc" id="L654">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L655">        } catch (AssertionError ex) {</span>
            // expected
        }

<span class="fc" id="L659">    }</span>

    @Test(timeout = 5000)
    public void await() throws Exception {
<span class="fc" id="L663">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>

<span class="fc" id="L665">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L667">        assertFalse(to.await(100, TimeUnit.MILLISECONDS));</span>

<span class="fc" id="L669">        to.awaitDone(100, TimeUnit.MILLISECONDS);</span>

<span class="fc" id="L671">        assertTrue(to.isDisposed());</span>

<span class="fc" id="L673">        assertFalse(to.awaitTerminalEvent(100, TimeUnit.MILLISECONDS));</span>

<span class="fc" id="L675">        assertEquals(0, to.completions());</span>
<span class="fc" id="L676">        assertEquals(0, to.errorCount());</span>

<span class="fc" id="L678">        to.onComplete();</span>

<span class="fc" id="L680">        assertTrue(to.await(100, TimeUnit.MILLISECONDS));</span>

<span class="fc" id="L682">        to.await();</span>

<span class="fc" id="L684">        to.awaitDone(5, TimeUnit.SECONDS);</span>

<span class="fc" id="L686">        assertEquals(1, to.completions());</span>
<span class="fc" id="L687">        assertEquals(0, to.errorCount());</span>

<span class="fc" id="L689">        assertTrue(to.awaitTerminalEvent());</span>

<span class="fc" id="L691">        final TestObserver&lt;Integer&gt; to1 = TestObserver.create();</span>

<span class="fc" id="L693">        to1.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L695">        Schedulers.single().scheduleDirect(new Runnable() {</span>
            @Override
            public void run() {
<span class="fc" id="L698">                to1.onComplete();</span>
<span class="fc" id="L699">            }</span>
        }, 200, TimeUnit.MILLISECONDS);

<span class="fc" id="L702">        to1.await();</span>

<span class="fc" id="L704">        to1.assertValueSet(Collections.&lt;Integer&gt;emptySet());</span>
<span class="fc" id="L705">    }</span>

    @Test
    public void errors() {
<span class="fc" id="L709">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>

<span class="fc" id="L711">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L713">        assertEquals(0, to.errors().size());</span>

<span class="fc" id="L715">        to.onError(new TestException());</span>

<span class="fc" id="L717">        assertEquals(1, to.errors().size());</span>

<span class="fc" id="L719">        TestHelper.assertError(to.errors(), 0, TestException.class);</span>
<span class="fc" id="L720">    }</span>

    @SuppressWarnings(&quot;unchecked&quot;)
    @Test
    public void onNext() {
<span class="fc" id="L725">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>

<span class="fc" id="L727">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L729">        assertEquals(0, to.valueCount());</span>

<span class="fc" id="L731">        assertEquals(Collections.emptyList(), to.values());</span>

<span class="fc" id="L733">        to.onNext(1);</span>

<span class="fc" id="L735">        assertEquals(Collections.singletonList(1), to.values());</span>

<span class="fc" id="L737">        to.cancel();</span>

<span class="fc" id="L739">        assertTrue(to.isCancelled());</span>
<span class="fc" id="L740">        assertTrue(to.isDisposed());</span>

<span class="fc" id="L742">        to.assertValue(1);</span>

<span class="fc" id="L744">        assertEquals(Arrays.asList(Collections.singletonList(1), Collections.emptyList(), Collections.emptyList()), to.getEvents());</span>

<span class="fc" id="L746">        to.onComplete();</span>

<span class="fc" id="L748">        assertEquals(Arrays.asList(Collections.singletonList(1), Collections.emptyList(), Collections.singletonList(Notification.createOnComplete())), to.getEvents());</span>
<span class="fc" id="L749">    }</span>

    @Test
    public void fusionModeToString() {
<span class="fc" id="L753">        assertEquals(&quot;NONE&quot;, TestObserver.fusionModeToString(QueueFuseable.NONE));</span>
<span class="fc" id="L754">        assertEquals(&quot;SYNC&quot;, TestObserver.fusionModeToString(QueueFuseable.SYNC));</span>
<span class="fc" id="L755">        assertEquals(&quot;ASYNC&quot;, TestObserver.fusionModeToString(QueueFuseable.ASYNC));</span>
<span class="fc" id="L756">        assertEquals(&quot;Unknown(100)&quot;, TestObserver.fusionModeToString(100));</span>
<span class="fc" id="L757">    }</span>

    @Test
    public void multipleTerminals() {
<span class="fc" id="L761">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>

<span class="fc" id="L763">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L765">        to.assertNotComplete();</span>

<span class="fc" id="L767">        to.onComplete();</span>

        try {
<span class="nc" id="L770">            to.assertNotComplete();</span>
<span class="nc" id="L771">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L772">        } catch (Throwable ex) {</span>
            // expected
        }

<span class="fc" id="L776">        to.assertTerminated();</span>

<span class="fc" id="L778">        to.onComplete();</span>

        try {
<span class="nc" id="L781">            to.assertComplete();</span>
<span class="nc" id="L782">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L783">        } catch (Throwable ex) {</span>
            // expected
        }

        try {
<span class="nc" id="L788">            to.assertTerminated();</span>
<span class="nc" id="L789">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L790">        } catch (Throwable ex) {</span>
            // expected
        }

        try {
<span class="nc" id="L795">            to.assertNotComplete();</span>
<span class="nc" id="L796">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L797">        } catch (Throwable ex) {</span>
            // expected
        }
<span class="fc" id="L800">    }</span>

    @Test
    public void assertValue() {
<span class="fc" id="L804">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>

<span class="fc" id="L806">        to.onSubscribe(Disposables.empty());</span>

        try {
<span class="nc" id="L809">            to.assertValue(1);</span>
<span class="nc" id="L810">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L811">        } catch (Throwable ex) {</span>
            // expected
        }

<span class="fc" id="L815">        to.onNext(1);</span>

<span class="fc" id="L817">        to.assertValue(1);</span>

        try {
<span class="nc" id="L820">            to.assertValue(2);</span>
<span class="nc" id="L821">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L822">        } catch (Throwable ex) {</span>
            // expected
        }

<span class="fc" id="L826">        to.onNext(2);</span>

        try {
<span class="nc" id="L829">            to.assertValue(1);</span>
<span class="nc" id="L830">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L831">        } catch (Throwable ex) {</span>
            // expected
        }
<span class="fc" id="L834">    }</span>

    @Test
    public void onNextMisbehave() {
<span class="fc" id="L838">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>

<span class="fc" id="L840">        to.onNext(1);</span>

<span class="fc" id="L842">        to.assertError(IllegalStateException.class);</span>

<span class="fc" id="L844">        to = TestObserver.create();</span>

<span class="fc" id="L846">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L848">        to.onNext(null);</span>

<span class="fc" id="L850">        to.assertFailure(NullPointerException.class, (Integer)null);</span>
<span class="fc" id="L851">    }</span>

    @Test
    public void awaitTerminalEventInterrupt() {
<span class="fc" id="L855">        final TestObserver&lt;Integer&gt; to = TestObserver.create();</span>

<span class="fc" id="L857">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L859">        Thread.currentThread().interrupt();</span>

<span class="fc" id="L861">        to.awaitTerminalEvent();</span>

<span class="fc" id="L863">        assertTrue(Thread.interrupted());</span>

<span class="fc" id="L865">        Thread.currentThread().interrupt();</span>

<span class="fc" id="L867">        to.awaitTerminalEvent(5, TimeUnit.SECONDS);</span>

<span class="fc" id="L869">        assertTrue(Thread.interrupted());</span>
<span class="fc" id="L870">    }</span>

    @Test
    public void assertTerminated2() {
<span class="fc" id="L874">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>

<span class="fc" id="L876">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L878">        assertFalse(to.isTerminated());</span>

<span class="fc" id="L880">        to.onError(new TestException());</span>
<span class="fc" id="L881">        to.onError(new IOException());</span>

<span class="fc" id="L883">        assertTrue(to.isTerminated());</span>

        try {
<span class="nc" id="L886">            to.assertTerminated();</span>
<span class="nc" id="L887">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L888">        } catch (AssertionError ex) {</span>
            // expected
        }

        try {
<span class="nc" id="L893">            to.assertError(TestException.class);</span>
<span class="nc" id="L894">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L895">        } catch (AssertionError ex) {</span>
            // expected
        }

<span class="fc" id="L899">        to = TestObserver.create();</span>

<span class="fc" id="L901">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L903">        to.onError(new TestException());</span>
<span class="fc" id="L904">        to.onComplete();</span>

        try {
<span class="nc" id="L907">            to.assertTerminated();</span>
<span class="nc" id="L908">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L909">        } catch (AssertionError ex) {</span>
            // expected
        }
<span class="fc" id="L912">    }</span>

    @Test
    public void onSubscribe() {
<span class="fc" id="L916">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>

<span class="fc" id="L918">        to.onSubscribe(null);</span>

<span class="fc" id="L920">        to.assertError(NullPointerException.class);</span>

<span class="fc" id="L922">        to = TestObserver.create();</span>

<span class="fc" id="L924">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L926">        Disposable d1 = Disposables.empty();</span>

<span class="fc" id="L928">        to.onSubscribe(d1);</span>

<span class="fc" id="L930">        assertTrue(d1.isDisposed());</span>

<span class="fc" id="L932">        to.assertError(IllegalStateException.class);</span>

<span class="fc" id="L934">        to = TestObserver.create();</span>
<span class="fc" id="L935">        to.dispose();</span>

<span class="fc" id="L937">        d1 = Disposables.empty();</span>

<span class="fc" id="L939">        to.onSubscribe(d1);</span>

<span class="fc" id="L941">        assertTrue(d1.isDisposed());</span>

<span class="fc" id="L943">    }</span>

    @Test
    public void assertValueSequence() {
<span class="fc" id="L947">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>

<span class="fc" id="L949">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L951">        to.onNext(1);</span>
<span class="fc" id="L952">        to.onNext(2);</span>

        try {
<span class="nc" id="L955">            to.assertValueSequence(Collections.&lt;Integer&gt;emptyList());</span>
<span class="nc" id="L956">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L957">        } catch (AssertionError expected) {</span>
<span class="fc" id="L958">            assertTrue(expected.getMessage(), expected.getMessage().startsWith(&quot;More values received than expected (0)&quot;));</span>
        }

        try {
<span class="nc" id="L962">            to.assertValueSequence(Collections.singletonList(1));</span>
<span class="nc" id="L963">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L964">        } catch (AssertionError expected) {</span>
<span class="fc" id="L965">            assertTrue(expected.getMessage(), expected.getMessage().startsWith(&quot;More values received than expected (1)&quot;));</span>
        }

<span class="fc" id="L968">        to.assertValueSequence(Arrays.asList(1, 2));</span>

        try {
<span class="nc" id="L971">            to.assertValueSequence(Arrays.asList(1, 2, 3));</span>
<span class="nc" id="L972">            throw new RuntimeException(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L973">        } catch (AssertionError expected) {</span>
<span class="fc" id="L974">            assertTrue(expected.getMessage(), expected.getMessage().startsWith(&quot;Fewer values received than expected (2)&quot;));</span>
        }
<span class="fc" id="L976">    }</span>

    @Test
    public void assertEmpty() {
<span class="fc" id="L980">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

        try {
<span class="nc" id="L983">            to.assertEmpty();</span>
<span class="nc" id="L984">            throw new RuntimeException(&quot;Should have thrown!&quot;);</span>
<span class="fc" id="L985">        } catch (AssertionError ex) {</span>
            // expected
        }

<span class="fc" id="L989">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L991">        to.assertEmpty();</span>

<span class="fc" id="L993">        to.onNext(1);</span>

        try {
<span class="nc" id="L996">            to.assertEmpty();</span>
<span class="nc" id="L997">            throw new RuntimeException(&quot;Should have thrown!&quot;);</span>
<span class="fc" id="L998">        } catch (AssertionError ex) {</span>
            // expected
        }
<span class="fc" id="L1001">    }</span>

    @Test
    public void awaitDoneTimed() {
<span class="fc" id="L1005">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L1007">        Thread.currentThread().interrupt();</span>

        try {
<span class="nc" id="L1010">            to.awaitDone(5, TimeUnit.SECONDS);</span>
<span class="fc" id="L1011">        } catch (RuntimeException ex) {</span>
<span class="fc" id="L1012">            assertTrue(ex.toString(), ex.getCause() instanceof InterruptedException);</span>
<span class="nc" id="L1013">        }</span>
<span class="fc" id="L1014">    }</span>

    @Test
    public void assertNotSubscribed() {
<span class="fc" id="L1018">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L1020">        to.assertNotSubscribed();</span>

<span class="fc" id="L1022">        to.errors().add(new TestException());</span>

        try {
<span class="nc" id="L1025">            to.assertNotSubscribed();</span>
<span class="nc" id="L1026">            throw new RuntimeException(&quot;Should have thrown!&quot;);</span>
<span class="fc" id="L1027">        } catch (AssertionError ex) {</span>
            // expected
        }
<span class="fc" id="L1030">    }</span>

    @Test
    public void assertErrorMultiple() {
<span class="fc" id="L1034">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L1036">        TestException e = new TestException();</span>
<span class="fc" id="L1037">        to.errors().add(e);</span>
<span class="fc" id="L1038">        to.errors().add(new TestException());</span>

        try {
<span class="nc" id="L1041">            to.assertError(TestException.class);</span>
<span class="nc" id="L1042">            throw new RuntimeException(&quot;Should have thrown!&quot;);</span>
<span class="fc" id="L1043">        } catch (AssertionError ex) {</span>
            // expected
        }
        try {
<span class="nc" id="L1047">            to.assertError(e);</span>
<span class="nc" id="L1048">            throw new RuntimeException(&quot;Should have thrown!&quot;);</span>
<span class="fc" id="L1049">        } catch (AssertionError ex) {</span>
            // expected
        }
        try {
<span class="nc" id="L1053">            to.assertError(Functions.&lt;Throwable&gt;alwaysTrue());</span>
<span class="nc" id="L1054">            throw new RuntimeException(&quot;Should have thrown!&quot;);</span>
<span class="fc" id="L1055">        } catch (AssertionError ex) {</span>
            // expected
        }
        try {
<span class="nc" id="L1059">            to.assertErrorMessage(&quot;&quot;);</span>
<span class="nc" id="L1060">            throw new RuntimeException(&quot;Should have thrown!&quot;);</span>
<span class="fc" id="L1061">        } catch (AssertionError ex) {</span>
            // expected
        }
<span class="fc" id="L1064">    }</span>

    @Test
    public void testErrorInPredicate() {
<span class="fc" id="L1068">        TestObserver&lt;Object&gt; to = new TestObserver&lt;Object&gt;();</span>
<span class="fc" id="L1069">        to.onError(new RuntimeException());</span>
        try {
<span class="pc" id="L1071">            to.assertError(new Predicate&lt;Throwable&gt;() {</span>
                @Override
                public boolean test(Throwable throwable) throws Exception {
<span class="fc" id="L1074">                    throw new TestException();</span>
                }
            });
<span class="fc" id="L1077">        } catch (TestException ex) {</span>
            // expected
<span class="fc" id="L1079">            return;</span>
<span class="nc" id="L1080">        }</span>
<span class="nc" id="L1081">        fail(&quot;Error in predicate but not thrown!&quot;);</span>
<span class="nc" id="L1082">    }</span>

    @Test
    public void assertComplete() {
<span class="fc" id="L1086">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L1088">        to.onSubscribe(Disposables.empty());</span>

        try {
<span class="nc" id="L1091">            to.assertComplete();</span>
<span class="nc" id="L1092">            throw new RuntimeException(&quot;Should have thrown!&quot;);</span>
<span class="fc" id="L1093">        } catch (AssertionError ex) {</span>
            // expected
        }

<span class="fc" id="L1097">        to.onComplete();</span>

<span class="fc" id="L1099">        to.assertComplete();</span>

<span class="fc" id="L1101">        to.onComplete();</span>

        try {
<span class="nc" id="L1104">            to.assertComplete();</span>
<span class="nc" id="L1105">            throw new RuntimeException(&quot;Should have thrown!&quot;);</span>
<span class="fc" id="L1106">        } catch (AssertionError ex) {</span>
            // expected
        }
<span class="fc" id="L1109">    }</span>

    @Test
    public void completeWithoutOnSubscribe() {
<span class="fc" id="L1113">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L1115">        to.onComplete();</span>

<span class="fc" id="L1117">        to.assertError(IllegalStateException.class);</span>
<span class="fc" id="L1118">    }</span>

    @Test
    public void completeDelegateThrows() {
<span class="fc" id="L1122">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;(new Observer&lt;Integer&gt;() {</span>

            @Override
            public void onSubscribe(Disposable d) {

<span class="fc" id="L1127">            }</span>

            @Override
            public void onNext(Integer value) {

<span class="nc" id="L1132">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="nc" id="L1136">                throw new TestException();</span>
            }

            @Override
            public void onComplete() {
<span class="fc" id="L1141">                throw new TestException();</span>
            }

        });

<span class="fc" id="L1146">        to.onSubscribe(Disposables.empty());</span>

        try {
<span class="nc" id="L1149">            to.onComplete();</span>
<span class="nc" id="L1150">            throw new RuntimeException(&quot;Should have thrown!&quot;);</span>
<span class="fc" id="L1151">        } catch (TestException ex) {</span>
<span class="fc" id="L1152">            assertTrue(to.isTerminated());</span>
        }
<span class="fc" id="L1154">    }</span>

    @Test
    public void errorDelegateThrows() {
<span class="fc" id="L1158">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;(new Observer&lt;Integer&gt;() {</span>

            @Override
            public void onSubscribe(Disposable d) {

<span class="fc" id="L1163">            }</span>

            @Override
            public void onNext(Integer value) {

<span class="nc" id="L1168">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="fc" id="L1172">                throw new TestException();</span>
            }

            @Override
            public void onComplete() {
<span class="nc" id="L1177">                throw new TestException();</span>
            }

        });

<span class="fc" id="L1182">        to.onSubscribe(Disposables.empty());</span>

        try {
<span class="nc" id="L1185">            to.onError(new IOException());</span>
<span class="nc" id="L1186">            throw new RuntimeException(&quot;Should have thrown!&quot;);</span>
<span class="fc" id="L1187">        } catch (TestException ex) {</span>
<span class="fc" id="L1188">            assertTrue(to.isTerminated());</span>
        }
<span class="fc" id="L1190">    }</span>

    @Test
    public void syncQueueThrows() {
<span class="fc" id="L1194">        TestObserver&lt;Object&gt; to = new TestObserver&lt;Object&gt;();</span>
<span class="fc" id="L1195">        to.setInitialFusionMode(QueueFuseable.SYNC);</span>

<span class="fc" id="L1197">        Observable.range(1, 5)</span>
<span class="fc" id="L1198">        .map(new Function&lt;Integer, Object&gt;() {</span>
            @Override
<span class="fc" id="L1200">            public Object apply(Integer v) throws Exception { throw new TestException(); }</span>
        })
<span class="fc" id="L1202">        .subscribe(to);</span>

<span class="fc" id="L1204">        to.assertSubscribed()</span>
<span class="fc" id="L1205">        .assertFuseable()</span>
<span class="fc" id="L1206">        .assertFusionMode(QueueFuseable.SYNC)</span>
<span class="fc" id="L1207">        .assertFailure(TestException.class);</span>
<span class="fc" id="L1208">    }</span>

    @Test
    public void asyncQueueThrows() {
<span class="fc" id="L1212">        TestObserver&lt;Object&gt; to = new TestObserver&lt;Object&gt;();</span>
<span class="fc" id="L1213">        to.setInitialFusionMode(QueueFuseable.ANY);</span>

<span class="fc" id="L1215">        UnicastSubject&lt;Integer&gt; up = UnicastSubject.create();</span>

<span class="fc" id="L1217">        up</span>
<span class="fc" id="L1218">        .map(new Function&lt;Integer, Object&gt;() {</span>
            @Override
<span class="fc" id="L1220">            public Object apply(Integer v) throws Exception { throw new TestException(); }</span>
        })
<span class="fc" id="L1222">        .subscribe(to);</span>

<span class="fc" id="L1224">        up.onNext(1);</span>

<span class="fc" id="L1226">        to.assertSubscribed()</span>
<span class="fc" id="L1227">        .assertFuseable()</span>
<span class="fc" id="L1228">        .assertFusionMode(QueueFuseable.ASYNC)</span>
<span class="fc" id="L1229">        .assertFailure(TestException.class);</span>
<span class="fc" id="L1230">    }</span>

    @Test
    public void completedMeansDisposed() {
        // 2.0.2 - a terminated TestObserver no longer reports isDisposed
<span class="fc" id="L1235">        assertFalse(Observable.just(1)</span>
<span class="fc" id="L1236">                .test()</span>
<span class="fc" id="L1237">                .assertResult(1).isDisposed());</span>
<span class="fc" id="L1238">    }</span>

    @Test
    public void errorMeansDisposed() {
        // 2.0.2 - a terminated TestObserver no longer reports isDisposed
<span class="fc" id="L1243">        assertFalse(Observable.error(new TestException())</span>
<span class="fc" id="L1244">                .test()</span>
<span class="fc" id="L1245">                .assertFailure(TestException.class).isDisposed());</span>
<span class="fc" id="L1246">    }</span>

    @Test
    public void asyncFusion() {
<span class="fc" id="L1250">        TestObserver&lt;Object&gt; to = new TestObserver&lt;Object&gt;();</span>
<span class="fc" id="L1251">        to.setInitialFusionMode(QueueFuseable.ANY);</span>

<span class="fc" id="L1253">        UnicastSubject&lt;Integer&gt; up = UnicastSubject.create();</span>

<span class="fc" id="L1255">        up</span>
<span class="fc" id="L1256">        .subscribe(to);</span>

<span class="fc" id="L1258">        up.onNext(1);</span>
<span class="fc" id="L1259">        up.onComplete();</span>

<span class="fc" id="L1261">        to.assertSubscribed()</span>
<span class="fc" id="L1262">        .assertFuseable()</span>
<span class="fc" id="L1263">        .assertFusionMode(QueueFuseable.ASYNC)</span>
<span class="fc" id="L1264">        .assertResult(1);</span>
<span class="fc" id="L1265">    }</span>

    @Test
    public void assertValuePredicateEmpty() {
<span class="fc" id="L1269">        TestObserver&lt;Object&gt; to = new TestObserver&lt;Object&gt;();</span>

<span class="fc" id="L1271">        Observable.empty().subscribe(to);</span>

<span class="fc" id="L1273">        thrown.expect(AssertionError.class);</span>
<span class="fc" id="L1274">        thrown.expectMessage(&quot;No values&quot;);</span>
<span class="pc" id="L1275">        to.assertValue(new Predicate&lt;Object&gt;() {</span>
            @Override public boolean test(final Object o) throws Exception {
<span class="nc" id="L1277">                return false;</span>
            }
        });
<span class="nc" id="L1280">    }</span>

    @Test
    public void assertValuePredicateMatch() {
<span class="fc" id="L1284">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L1286">        Observable.just(1).subscribe(to);</span>

<span class="fc" id="L1288">        to.assertValue(new Predicate&lt;Integer&gt;() {</span>
            @Override public boolean test(final Integer o) throws Exception {
<span class="pc bpc" id="L1290" title="1 of 2 branches missed.">                return o == 1;</span>
            }
        });
<span class="fc" id="L1293">    }</span>

    @Test
    public void assertValuePredicateNoMatch() {
<span class="fc" id="L1297">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L1299">        Observable.just(1).subscribe(to);</span>

<span class="fc" id="L1301">        thrown.expect(AssertionError.class);</span>
<span class="fc" id="L1302">        thrown.expectMessage(&quot;Value not present&quot;);</span>
<span class="pc" id="L1303">        to.assertValue(new Predicate&lt;Integer&gt;() {</span>
            @Override public boolean test(final Integer o) throws Exception {
<span class="pc bpc" id="L1305" title="1 of 2 branches missed.">                return o != 1;</span>
            }
        });
<span class="nc" id="L1308">    }</span>

    @Test
    public void assertValuePredicateMatchButMore() {
<span class="fc" id="L1312">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L1314">        Observable.just(1, 2).subscribe(to);</span>

<span class="fc" id="L1316">        thrown.expect(AssertionError.class);</span>
<span class="fc" id="L1317">        thrown.expectMessage(&quot;Value present but other values as well&quot;);</span>
<span class="pc" id="L1318">        to.assertValue(new Predicate&lt;Integer&gt;() {</span>
            @Override public boolean test(final Integer o) throws Exception {
<span class="pc bpc" id="L1320" title="1 of 2 branches missed.">                return o == 1;</span>
            }
        });
<span class="nc" id="L1323">    }</span>

    @Test
    public void assertValueAtPredicateEmpty() {
<span class="fc" id="L1327">        TestObserver&lt;Object&gt; to = new TestObserver&lt;Object&gt;();</span>

<span class="fc" id="L1329">        Observable.empty().subscribe(to);</span>

<span class="fc" id="L1331">        thrown.expect(AssertionError.class);</span>
<span class="fc" id="L1332">        thrown.expectMessage(&quot;No values&quot;);</span>
<span class="pc" id="L1333">        to.assertValueAt(0, new Predicate&lt;Object&gt;() {</span>
            @Override public boolean test(final Object o) throws Exception {
<span class="nc" id="L1335">                return false;</span>
            }
        });
<span class="nc" id="L1338">    }</span>

    @Test
    public void assertValueAtPredicateMatch() {
<span class="fc" id="L1342">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L1344">        Observable.just(1, 2).subscribe(to);</span>

<span class="fc" id="L1346">        to.assertValueAt(1, new Predicate&lt;Integer&gt;() {</span>
            @Override public boolean test(final Integer o) throws Exception {
<span class="pc bpc" id="L1348" title="1 of 2 branches missed.">                return o == 2;</span>
            }
        });
<span class="fc" id="L1351">    }</span>

    @Test
    public void assertValueAtPredicateNoMatch() {
<span class="fc" id="L1355">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L1357">        Observable.just(1, 2, 3).subscribe(to);</span>

<span class="fc" id="L1359">        thrown.expect(AssertionError.class);</span>
<span class="fc" id="L1360">        thrown.expectMessage(&quot;Value not present&quot;);</span>
<span class="pc" id="L1361">        to.assertValueAt(2, new Predicate&lt;Integer&gt;() {</span>
            @Override public boolean test(final Integer o) throws Exception {
<span class="pc bpc" id="L1363" title="1 of 2 branches missed.">                return o != 3;</span>
            }
        });
<span class="nc" id="L1366">    }</span>

    @Test
    public void assertValueAtInvalidIndex() {
<span class="fc" id="L1370">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L1372">        Observable.just(1, 2).subscribe(to);</span>

<span class="fc" id="L1374">        thrown.expect(AssertionError.class);</span>
<span class="fc" id="L1375">        thrown.expectMessage(&quot;Invalid index: 2 (latch = 0, values = 2, errors = 0, completions = 1)&quot;);</span>
<span class="pc" id="L1376">        to.assertValueAt(2, new Predicate&lt;Integer&gt;() {</span>
            @Override public boolean test(final Integer o) throws Exception {
<span class="nc bnc" id="L1378" title="All 2 branches missed.">                return o == 1;</span>
            }
        });
<span class="nc" id="L1381">    }</span>

    @Test
    public void assertValueAtIndexEmpty() {
<span class="fc" id="L1385">        TestObserver&lt;Object&gt; to = new TestObserver&lt;Object&gt;();</span>

<span class="fc" id="L1387">        Observable.empty().subscribe(to);</span>

<span class="fc" id="L1389">        thrown.expect(AssertionError.class);</span>
<span class="fc" id="L1390">        thrown.expectMessage(&quot;No values&quot;);</span>
<span class="nc" id="L1391">        to.assertValueAt(0, &quot;a&quot;);</span>
<span class="nc" id="L1392">    }</span>

    @Test
    public void assertValueAtIndexMatch() {
<span class="fc" id="L1396">        TestObserver&lt;String&gt; to = new TestObserver&lt;String&gt;();</span>

<span class="fc" id="L1398">        Observable.just(&quot;a&quot;, &quot;b&quot;).subscribe(to);</span>

<span class="fc" id="L1400">        to.assertValueAt(1, &quot;b&quot;);</span>
<span class="fc" id="L1401">    }</span>

    @Test
    public void assertValueAtIndexNoMatch() {
<span class="fc" id="L1405">        TestObserver&lt;String&gt; to = new TestObserver&lt;String&gt;();</span>

<span class="fc" id="L1407">        Observable.just(&quot;a&quot;, &quot;b&quot;, &quot;c&quot;).subscribe(to);</span>

<span class="fc" id="L1409">        thrown.expect(AssertionError.class);</span>
<span class="fc" id="L1410">        thrown.expectMessage(&quot;expected: b (class: String) but was: c (class: String) (latch = 0, values = 3, errors = 0, completions = 1)&quot;);</span>
<span class="nc" id="L1411">        to.assertValueAt(2, &quot;b&quot;);</span>
<span class="nc" id="L1412">    }</span>

    @Test
    public void assertValueAtIndexInvalidIndex() {
<span class="fc" id="L1416">        TestObserver&lt;String&gt; to = new TestObserver&lt;String&gt;();</span>

<span class="fc" id="L1418">        Observable.just(&quot;a&quot;, &quot;b&quot;).subscribe(to);</span>

<span class="fc" id="L1420">        thrown.expect(AssertionError.class);</span>
<span class="fc" id="L1421">        thrown.expectMessage(&quot;Invalid index: 2 (latch = 0, values = 2, errors = 0, completions = 1)&quot;);</span>
<span class="nc" id="L1422">        to.assertValueAt(2, &quot;c&quot;);</span>
<span class="nc" id="L1423">    }</span>

    @Test
    public void withTag() {
        try {
<span class="pc bpc" id="L1428" title="1 of 2 branches missed.">            for (int i = 1; i &lt; 3; i++) {</span>
<span class="fc" id="L1429">                Observable.just(i)</span>
<span class="fc" id="L1430">                .test()</span>
<span class="fc" id="L1431">                .withTag(&quot;testing with item=&quot; + i)</span>
<span class="fc" id="L1432">                .assertResult(1)</span>
                ;
            }
<span class="nc" id="L1435">            throw new RuntimeException(&quot;Should have thrown!&quot;);</span>
<span class="fc" id="L1436">        } catch (AssertionError ex) {</span>
<span class="fc" id="L1437">            assertTrue(ex.toString(), ex.toString().contains(&quot;testing with item=2&quot;));</span>
        }
<span class="fc" id="L1439">    }</span>

    @Test
    public void assertValuesOnly() {
<span class="fc" id="L1443">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>
<span class="fc" id="L1444">        to.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L1445">        to.assertValuesOnly();</span>

<span class="fc" id="L1447">        to.onNext(5);</span>
<span class="fc" id="L1448">        to.assertValuesOnly(5);</span>

<span class="fc" id="L1450">        to.onNext(-1);</span>
<span class="fc" id="L1451">        to.assertValuesOnly(5, -1);</span>
<span class="fc" id="L1452">    }</span>

    @Test
    public void assertValuesOnlyThrowsOnUnexpectedValue() {
<span class="fc" id="L1456">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>
<span class="fc" id="L1457">        to.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L1458">        to.assertValuesOnly();</span>

<span class="fc" id="L1460">        to.onNext(5);</span>
<span class="fc" id="L1461">        to.assertValuesOnly(5);</span>

<span class="fc" id="L1463">        to.onNext(-1);</span>

        try {
<span class="nc" id="L1466">            to.assertValuesOnly(5);</span>
<span class="nc" id="L1467">            throw new RuntimeException();</span>
<span class="fc" id="L1468">        } catch (AssertionError ex) {</span>
            // expected
        }
<span class="fc" id="L1471">    }</span>

    @Test
    public void assertValuesOnlyThrowsWhenCompleted() {
<span class="fc" id="L1475">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>
<span class="fc" id="L1476">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L1478">        to.onComplete();</span>

        try {
<span class="nc" id="L1481">            to.assertValuesOnly();</span>
<span class="nc" id="L1482">            throw new RuntimeException();</span>
<span class="fc" id="L1483">        } catch (AssertionError ex) {</span>
            // expected
        }
<span class="fc" id="L1486">    }</span>

    @Test
    public void assertValuesOnlyThrowsWhenErrored() {
<span class="fc" id="L1490">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>
<span class="fc" id="L1491">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L1493">        to.onError(new TestException());</span>

        try {
<span class="nc" id="L1496">            to.assertValuesOnly();</span>
<span class="nc" id="L1497">            throw new RuntimeException();</span>
<span class="fc" id="L1498">        } catch (AssertionError ex) {</span>
            // expected
        }
<span class="fc" id="L1501">    }</span>

    @Test
    public void assertValueSetOnly() {
<span class="fc" id="L1505">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>
<span class="fc" id="L1506">        to.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L1507">        to.assertValueSetOnly(Collections.&lt;Integer&gt;emptySet());</span>

<span class="fc" id="L1509">        to.onNext(5);</span>
<span class="fc" id="L1510">        to.assertValueSetOnly(Collections.singleton(5));</span>

<span class="fc" id="L1512">        to.onNext(-1);</span>
<span class="fc" id="L1513">        to.assertValueSetOnly(new HashSet&lt;Integer&gt;(Arrays.asList(5, -1)));</span>
<span class="fc" id="L1514">    }</span>

    @Test
    public void assertValueSetOnlyThrowsOnUnexpectedValue() {
<span class="fc" id="L1518">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>
<span class="fc" id="L1519">        to.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L1520">        to.assertValueSetOnly(Collections.&lt;Integer&gt;emptySet());</span>

<span class="fc" id="L1522">        to.onNext(5);</span>
<span class="fc" id="L1523">        to.assertValueSetOnly(Collections.singleton(5));</span>

<span class="fc" id="L1525">        to.onNext(-1);</span>

        try {
<span class="nc" id="L1528">            to.assertValueSetOnly(Collections.singleton(5));</span>
<span class="nc" id="L1529">            throw new RuntimeException();</span>
<span class="fc" id="L1530">        } catch (AssertionError ex) {</span>
            // expected
        }
<span class="fc" id="L1533">    }</span>

    @Test
    public void assertValueSetOnlyThrowsWhenCompleted() {
<span class="fc" id="L1537">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>
<span class="fc" id="L1538">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L1540">        to.onComplete();</span>

        try {
<span class="nc" id="L1543">            to.assertValueSetOnly(Collections.&lt;Integer&gt;emptySet());</span>
<span class="nc" id="L1544">            throw new RuntimeException();</span>
<span class="fc" id="L1545">        } catch (AssertionError ex) {</span>
            // expected
        }
<span class="fc" id="L1548">    }</span>

    @Test
    public void assertValueSetOnlyThrowsWhenErrored() {
<span class="fc" id="L1552">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>
<span class="fc" id="L1553">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L1555">        to.onError(new TestException());</span>

        try {
<span class="nc" id="L1558">            to.assertValueSetOnly(Collections.&lt;Integer&gt;emptySet());</span>
<span class="nc" id="L1559">            throw new RuntimeException();</span>
<span class="fc" id="L1560">        } catch (AssertionError ex) {</span>
            // expected
        }
<span class="fc" id="L1563">    }</span>

    @Test
    public void assertValueSequenceOnly() {
<span class="fc" id="L1567">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>
<span class="fc" id="L1568">        to.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L1569">        to.assertValueSequenceOnly(Collections.&lt;Integer&gt;emptyList());</span>

<span class="fc" id="L1571">        to.onNext(5);</span>
<span class="fc" id="L1572">        to.assertValueSequenceOnly(Collections.singletonList(5));</span>

<span class="fc" id="L1574">        to.onNext(-1);</span>
<span class="fc" id="L1575">        to.assertValueSequenceOnly(Arrays.asList(5, -1));</span>
<span class="fc" id="L1576">    }</span>

    @Test
    public void assertValueSequenceOnlyThrowsOnUnexpectedValue() {
<span class="fc" id="L1580">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>
<span class="fc" id="L1581">        to.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L1582">        to.assertValueSequenceOnly(Collections.&lt;Integer&gt;emptyList());</span>

<span class="fc" id="L1584">        to.onNext(5);</span>
<span class="fc" id="L1585">        to.assertValueSequenceOnly(Collections.singletonList(5));</span>

<span class="fc" id="L1587">        to.onNext(-1);</span>

        try {
<span class="nc" id="L1590">            to.assertValueSequenceOnly(Collections.singletonList(5));</span>
<span class="nc" id="L1591">            throw new RuntimeException();</span>
<span class="fc" id="L1592">        } catch (AssertionError ex) {</span>
            // expected
        }
<span class="fc" id="L1595">    }</span>

    @Test
    public void assertValueSequenceOnlyThrowsWhenCompleted() {
<span class="fc" id="L1599">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>
<span class="fc" id="L1600">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L1602">        to.onComplete();</span>

        try {
<span class="nc" id="L1605">            to.assertValueSequenceOnly(Collections.&lt;Integer&gt;emptyList());</span>
<span class="nc" id="L1606">            throw new RuntimeException();</span>
<span class="fc" id="L1607">        } catch (AssertionError ex) {</span>
            // expected
        }
<span class="fc" id="L1610">    }</span>

    @Test
    public void assertValueSequenceOnlyThrowsWhenErrored() {
<span class="fc" id="L1614">        TestObserver&lt;Integer&gt; to = TestObserver.create();</span>
<span class="fc" id="L1615">        to.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L1617">        to.onError(new TestException());</span>

        try {
<span class="nc" id="L1620">            to.assertValueSequenceOnly(Collections.&lt;Integer&gt;emptyList());</span>
<span class="nc" id="L1621">            throw new RuntimeException();</span>
<span class="fc" id="L1622">        } catch (AssertionError ex) {</span>
            // expected
        }
<span class="fc" id="L1625">    }</span>

    @Test
    public void assertValueSetWiderSet() {
<span class="fc" id="L1629">        Set&lt;Integer&gt; set = new HashSet&lt;Integer&gt;(Arrays.asList(0, 1, 2, 3, 4, 5, 6, 7));</span>

<span class="fc" id="L1631">        Observable.just(4, 5, 1, 3, 2)</span>
<span class="fc" id="L1632">        .test()</span>
<span class="fc" id="L1633">        .assertValueSet(set);</span>
<span class="fc" id="L1634">    }</span>

    @Test
    public void assertValueSetExact() {
<span class="fc" id="L1638">        Set&lt;Integer&gt; set = new HashSet&lt;Integer&gt;(Arrays.asList(1, 2, 3, 4, 5));</span>

<span class="fc" id="L1640">        Observable.just(4, 5, 1, 3, 2)</span>
<span class="fc" id="L1641">        .test()</span>
<span class="fc" id="L1642">        .assertValueSet(set)</span>
<span class="fc" id="L1643">        .assertValueCount(set.size());</span>
<span class="fc" id="L1644">    }</span>

    @Test
    public void assertValueSetMissing() {
<span class="fc" id="L1648">        Set&lt;Integer&gt; set = new HashSet&lt;Integer&gt;(Arrays.asList(0, 1, 2, 4, 5, 6, 7));</span>

        try {
<span class="fc" id="L1651">            Observable.range(1, 5)</span>
<span class="fc" id="L1652">            .test()</span>
<span class="nc" id="L1653">            .assertValueSet(set);</span>

<span class="nc" id="L1655">            throw new RuntimeException(&quot;Should have failed&quot;);</span>
<span class="fc" id="L1656">        } catch (AssertionError ex) {</span>
<span class="fc" id="L1657">            assertTrue(ex.getMessage(), ex.getMessage().contains(&quot;Value not in the expected collection: &quot; + 3));</span>
        }
<span class="fc" id="L1659">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>