<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>SafeSubscriberTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.subscribers</a> &gt; <span class="el_source">SafeSubscriberTest.java</span></div><h1>SafeSubscriberTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.subscribers;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

import java.util.List;
import java.util.concurrent.atomic.AtomicReference;

import org.junit.*;
import org.mockito.Mockito;
import org.reactivestreams.*;

import io.reactivex.*;
import io.reactivex.exceptions.*;
import io.reactivex.internal.subscriptions.BooleanSubscription;
import io.reactivex.plugins.RxJavaPlugins;

<span class="fc" id="L31">public class SafeSubscriberTest {</span>

    /**
     * Ensure onNext can not be called after onError.
     */
    @Test
    public void testOnNextAfterOnError() {
<span class="fc" id="L38">        TestObservable t = new TestObservable();</span>
<span class="fc" id="L39">        Flowable&lt;String&gt; st = Flowable.unsafeCreate(t);</span>

<span class="fc" id="L41">        Subscriber&lt;String&gt; w = TestHelper.mockSubscriber();</span>
<span class="fc" id="L42">        st.subscribe(new SafeSubscriber&lt;String&gt;(new TestSubscriber&lt;String&gt;(w)));</span>

<span class="fc" id="L44">        t.sendOnNext(&quot;one&quot;);</span>
<span class="fc" id="L45">        t.sendOnError(new RuntimeException(&quot;bad&quot;));</span>
<span class="fc" id="L46">        t.sendOnNext(&quot;two&quot;);</span>

<span class="fc" id="L48">        verify(w, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L49">        verify(w, times(1)).onError(any(Throwable.class));</span>
<span class="fc" id="L50">        verify(w, Mockito.never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L51">    }</span>

    /**
     * Ensure onComplete can not be called after onError.
     */
    @Test
    public void testOnCompletedAfterOnError() {
<span class="fc" id="L58">        TestObservable t = new TestObservable();</span>
<span class="fc" id="L59">        Flowable&lt;String&gt; st = Flowable.unsafeCreate(t);</span>

<span class="fc" id="L61">        Subscriber&lt;String&gt; w = TestHelper.mockSubscriber();</span>

<span class="fc" id="L63">        st.subscribe(new SafeSubscriber&lt;String&gt;(new TestSubscriber&lt;String&gt;(w)));</span>

<span class="fc" id="L65">        t.sendOnNext(&quot;one&quot;);</span>
<span class="fc" id="L66">        t.sendOnError(new RuntimeException(&quot;bad&quot;));</span>
<span class="fc" id="L67">        t.sendOnCompleted();</span>

<span class="fc" id="L69">        verify(w, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L70">        verify(w, times(1)).onError(any(Throwable.class));</span>
<span class="fc" id="L71">        verify(w, Mockito.never()).onComplete();</span>
<span class="fc" id="L72">    }</span>

    /**
     * Ensure onNext can not be called after onComplete.
     */
    @Test
    public void testOnNextAfterOnCompleted() {
<span class="fc" id="L79">        TestObservable t = new TestObservable();</span>
<span class="fc" id="L80">        Flowable&lt;String&gt; st = Flowable.unsafeCreate(t);</span>

<span class="fc" id="L82">        Subscriber&lt;String&gt; w = TestHelper.mockSubscriber();</span>
<span class="fc" id="L83">        st.subscribe(new SafeSubscriber&lt;String&gt;(new TestSubscriber&lt;String&gt;(w)));</span>

<span class="fc" id="L85">        t.sendOnNext(&quot;one&quot;);</span>
<span class="fc" id="L86">        t.sendOnCompleted();</span>
<span class="fc" id="L87">        t.sendOnNext(&quot;two&quot;);</span>

<span class="fc" id="L89">        verify(w, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L90">        verify(w, Mockito.never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L91">        verify(w, times(1)).onComplete();</span>
<span class="fc" id="L92">        verify(w, Mockito.never()).onError(any(Throwable.class));</span>
<span class="fc" id="L93">    }</span>

    /**
     * Ensure onError can not be called after onComplete.
     */
    @Test
    public void testOnErrorAfterOnCompleted() {
<span class="fc" id="L100">        TestObservable t = new TestObservable();</span>
<span class="fc" id="L101">        Flowable&lt;String&gt; st = Flowable.unsafeCreate(t);</span>

<span class="fc" id="L103">        Subscriber&lt;String&gt; w = TestHelper.mockSubscriber();</span>
<span class="fc" id="L104">        st.subscribe(new SafeSubscriber&lt;String&gt;(new TestSubscriber&lt;String&gt;(w)));</span>

<span class="fc" id="L106">        t.sendOnNext(&quot;one&quot;);</span>
<span class="fc" id="L107">        t.sendOnCompleted();</span>
<span class="fc" id="L108">        t.sendOnError(new RuntimeException(&quot;bad&quot;));</span>

<span class="fc" id="L110">        verify(w, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L111">        verify(w, times(1)).onComplete();</span>
<span class="fc" id="L112">        verify(w, Mockito.never()).onError(any(Throwable.class));</span>
<span class="fc" id="L113">    }</span>

    /**
     * An Observable that doesn't do the right thing on UnSubscribe/Error/etc in that it will keep sending events down the pipe regardless of what happens.
     */
    private static class TestObservable implements Publisher&lt;String&gt; {

        Subscriber&lt;? super String&gt; subscriber;

        /* used to simulate subscription */
        public void sendOnCompleted() {
<span class="fc" id="L124">            subscriber.onComplete();</span>
<span class="fc" id="L125">        }</span>

        /* used to simulate subscription */
        public void sendOnNext(String value) {
<span class="fc" id="L129">            subscriber.onNext(value);</span>
<span class="fc" id="L130">        }</span>

        /* used to simulate subscription */
        public void sendOnError(Throwable e) {
<span class="fc" id="L134">            subscriber.onError(e);</span>
<span class="fc" id="L135">        }</span>

        @Override
        public void subscribe(Subscriber&lt;? super String&gt; subscriber) {
<span class="fc" id="L139">            this.subscriber = subscriber;</span>
<span class="fc" id="L140">            subscriber.onSubscribe(new Subscription() {</span>

                @Override
                public void cancel() {
                    // going to do nothing to pretend I'm a bad Observable that keeps allowing events to be sent
<span class="nc" id="L145">                    System.out.println(&quot;==&gt; SynchronizeTest unsubscribe that does nothing!&quot;);</span>
<span class="nc" id="L146">                }</span>

                @Override
                public void request(long n) {

<span class="fc" id="L151">                }</span>

            });
<span class="fc" id="L154">        }</span>

    }

    @Test
    public void onNextFailure() {
<span class="fc" id="L160">        AtomicReference&lt;Throwable&gt; onError = new AtomicReference&lt;Throwable&gt;();</span>
        try {
<span class="nc" id="L162">            OBSERVER_ONNEXT_FAIL(onError).onNext(&quot;one&quot;);</span>
<span class="nc" id="L163">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="fc" id="L164">        } catch (Exception e) {</span>
<span class="fc" id="L165">            assertNull(onError.get());</span>
<span class="fc" id="L166">            assertTrue(e instanceof SafeSubscriberTestException);</span>
<span class="fc" id="L167">            assertEquals(&quot;onNextFail&quot;, e.getMessage());</span>
<span class="nc" id="L168">        }</span>
<span class="fc" id="L169">    }</span>

    @Test
    public void onNextFailureSafe() {
<span class="fc" id="L173">        AtomicReference&lt;Throwable&gt; onError = new AtomicReference&lt;Throwable&gt;();</span>
        try {
<span class="fc" id="L175">            SafeSubscriber&lt;String&gt; safeObserver = new SafeSubscriber&lt;String&gt;(OBSERVER_ONNEXT_FAIL(onError));</span>
<span class="fc" id="L176">            safeObserver.onSubscribe(new BooleanSubscription());</span>
<span class="fc" id="L177">            safeObserver.onNext(&quot;one&quot;);</span>
<span class="fc" id="L178">            assertNotNull(onError.get());</span>
<span class="fc" id="L179">            assertTrue(onError.get() instanceof SafeSubscriberTestException);</span>
<span class="fc" id="L180">            assertEquals(&quot;onNextFail&quot;, onError.get().getMessage());</span>
<span class="nc" id="L181">        } catch (Exception e) {</span>
<span class="nc" id="L182">            fail(&quot;expects exception to be passed to onError&quot;);</span>
<span class="fc" id="L183">        }</span>
<span class="fc" id="L184">    }</span>

    @Test
    public void onCompleteFailure() {
<span class="fc" id="L188">        AtomicReference&lt;Throwable&gt; onError = new AtomicReference&lt;Throwable&gt;();</span>
        try {
<span class="nc" id="L190">            OBSERVER_ONCOMPLETED_FAIL(onError).onComplete();</span>
<span class="nc" id="L191">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="fc" id="L192">        } catch (Exception e) {</span>
<span class="fc" id="L193">            assertNull(onError.get());</span>
<span class="fc" id="L194">            assertTrue(e instanceof SafeSubscriberTestException);</span>
<span class="fc" id="L195">            assertEquals(&quot;onCompleteFail&quot;, e.getMessage());</span>
<span class="nc" id="L196">        }</span>
<span class="fc" id="L197">    }</span>

    @Test
    public void onErrorFailure() {
        try {
<span class="nc" id="L202">            subscriberOnErrorFail().onError(new SafeSubscriberTestException(&quot;error!&quot;));</span>
<span class="nc" id="L203">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="fc" id="L204">        } catch (Exception e) {</span>
<span class="fc" id="L205">            assertTrue(e instanceof SafeSubscriberTestException);</span>
<span class="fc" id="L206">            assertEquals(&quot;onErrorFail&quot;, e.getMessage());</span>
<span class="nc" id="L207">        }</span>
<span class="fc" id="L208">    }</span>

    @Test
    @Ignore(&quot;Observers can't throw&quot;)
    public void onErrorFailureSafe() {
        try {
<span class="nc" id="L214">            new SafeSubscriber&lt;String&gt;(subscriberOnErrorFail()).onError(new SafeSubscriberTestException(&quot;error!&quot;));</span>
<span class="nc" id="L215">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="nc" id="L216">        } catch (Exception e) {</span>
<span class="nc" id="L217">            e.printStackTrace();</span>
<span class="nc" id="L218">            assertTrue(e instanceof RuntimeException);</span>
<span class="nc" id="L219">            assertEquals(&quot;Error occurred when trying to propagate error to Subscriber.onError&quot;, e.getMessage());</span>

<span class="nc" id="L221">            Throwable e2 = e.getCause();</span>
<span class="nc" id="L222">            assertTrue(e2 instanceof CompositeException);</span>
<span class="nc" id="L223">            List&lt;Throwable&gt; innerExceptions = ((CompositeException) e2).getExceptions();</span>
<span class="nc" id="L224">            assertEquals(2, innerExceptions.size());</span>

<span class="nc" id="L226">            Throwable e3 = innerExceptions.get(0);</span>
<span class="nc" id="L227">            assertTrue(e3 instanceof SafeSubscriberTestException);</span>
<span class="nc" id="L228">            assertEquals(&quot;error!&quot;, e3.getMessage());</span>

<span class="nc" id="L230">            Throwable e4 = innerExceptions.get(1);</span>
<span class="nc" id="L231">            assertTrue(e4 instanceof SafeSubscriberTestException);</span>
<span class="nc" id="L232">            assertEquals(&quot;onErrorFail&quot;, e4.getMessage());</span>
<span class="nc" id="L233">        }</span>
<span class="nc" id="L234">    }</span>

    @Test
    @Ignore(&quot;Observers can't throw&quot;)
    public void onErrorNotImplementedFailureSafe() {
        try {
<span class="nc" id="L240">            new SafeSubscriber&lt;String&gt;(subscriberOnErrorNotImplemented()).onError(new SafeSubscriberTestException(&quot;error!&quot;));</span>
<span class="nc" id="L241">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="nc" id="L242">        } catch (Exception e) {</span>
//            assertTrue(e instanceof OnErrorNotImplementedException);
<span class="nc" id="L244">            assertTrue(e.getCause() instanceof SafeSubscriberTestException);</span>
<span class="nc" id="L245">            assertEquals(&quot;error!&quot;, e.getCause().getMessage());</span>
<span class="nc" id="L246">        }</span>
<span class="nc" id="L247">    }</span>

    @Test
    public void onNextOnErrorFailure() {
        try {
<span class="nc" id="L252">            OBSERVER_ONNEXT_ONERROR_FAIL().onNext(&quot;one&quot;);</span>
<span class="nc" id="L253">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="fc" id="L254">        } catch (Exception e) {</span>
<span class="fc" id="L255">            e.printStackTrace();</span>
<span class="fc" id="L256">            assertTrue(e instanceof SafeSubscriberTestException);</span>
<span class="fc" id="L257">            assertEquals(&quot;onNextFail&quot;, e.getMessage());</span>
<span class="nc" id="L258">        }</span>
<span class="fc" id="L259">    }</span>

    @Test
    @Ignore(&quot;Observers can't throw&quot;)
    public void onNextOnErrorFailureSafe() {
        try {
<span class="nc" id="L265">            new SafeSubscriber&lt;String&gt;(OBSERVER_ONNEXT_ONERROR_FAIL()).onNext(&quot;one&quot;);</span>
<span class="nc" id="L266">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="nc" id="L267">        } catch (Exception e) {</span>
<span class="nc" id="L268">            e.printStackTrace();</span>
<span class="nc" id="L269">            assertTrue(e instanceof RuntimeException);</span>
<span class="nc" id="L270">            assertEquals(&quot;Error occurred when trying to propagate error to Subscriber.onError&quot;, e.getMessage());</span>

<span class="nc" id="L272">            Throwable e2 = e.getCause();</span>
<span class="nc" id="L273">            assertTrue(e2 instanceof CompositeException);</span>
<span class="nc" id="L274">            List&lt;Throwable&gt; innerExceptions = ((CompositeException) e2).getExceptions();</span>
<span class="nc" id="L275">            assertEquals(2, innerExceptions.size());</span>

<span class="nc" id="L277">            Throwable e3 = innerExceptions.get(0);</span>
<span class="nc" id="L278">            assertTrue(e3 instanceof SafeSubscriberTestException);</span>
<span class="nc" id="L279">            assertEquals(&quot;onNextFail&quot;, e3.getMessage());</span>

<span class="nc" id="L281">            Throwable e4 = innerExceptions.get(1);</span>
<span class="nc" id="L282">            assertTrue(e4 instanceof SafeSubscriberTestException);</span>
<span class="nc" id="L283">            assertEquals(&quot;onErrorFail&quot;, e4.getMessage());</span>
<span class="nc" id="L284">        }</span>
<span class="nc" id="L285">    }</span>

<span class="fc" id="L287">    static final Subscription THROWING_DISPOSABLE = new Subscription() {</span>

        @Override
        public void cancel() {
            // break contract by throwing exception
<span class="nc" id="L292">            throw new SafeSubscriberTestException(&quot;failure from unsubscribe&quot;);</span>
        }

        @Override
        public void request(long n) {
            // ignored
<span class="nc" id="L298">        }</span>
    };

    @Test
    @Ignore(&quot;Observers can't throw&quot;)
    public void onCompleteSuccessWithUnsubscribeFailure() {
<span class="nc" id="L304">        Subscriber&lt;String&gt; subscriber = subscriberSuccess();</span>
        try {
<span class="nc" id="L306">            subscriber.onSubscribe(THROWING_DISPOSABLE);</span>
<span class="nc" id="L307">            new SafeSubscriber&lt;String&gt;(subscriber).onComplete();</span>
<span class="nc" id="L308">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="nc" id="L309">        } catch (Exception e) {</span>
<span class="nc" id="L310">            e.printStackTrace();</span>

            // FIXME no longer assertable
//            assertTrue(o.isUnsubscribed());
//            assertTrue(e instanceof UnsubscribeFailedException);
<span class="nc" id="L315">            assertTrue(e.getCause() instanceof SafeSubscriberTestException);</span>
<span class="nc" id="L316">            assertEquals(&quot;failure from unsubscribe&quot;, e.getMessage());</span>
            // expected since onError fails so SafeSubscriber can't help
<span class="nc" id="L318">        }</span>
<span class="nc" id="L319">    }</span>

    @Test
    @Ignore(&quot;Observers can't throw&quot;)
    public void onErrorSuccessWithUnsubscribeFailure() {
<span class="nc" id="L324">        AtomicReference&lt;Throwable&gt; onError = new AtomicReference&lt;Throwable&gt;();</span>
<span class="nc" id="L325">        Subscriber&lt;String&gt; subscriber = subscriberSuccess(onError);</span>
        try {
<span class="nc" id="L327">            subscriber.onSubscribe(THROWING_DISPOSABLE);</span>
<span class="nc" id="L328">            new SafeSubscriber&lt;String&gt;(subscriber).onError(new SafeSubscriberTestException(&quot;failed&quot;));</span>
<span class="nc" id="L329">            fail(&quot;we expect the unsubscribe failure to cause an exception to be thrown&quot;);</span>
<span class="nc" id="L330">        } catch (Exception e) {</span>
<span class="nc" id="L331">            e.printStackTrace();</span>

            // FIXME no longer assertable
//            assertTrue(o.isUnsubscribed());

            // we still expect onError to have received something before unsubscribe blew up
<span class="nc" id="L337">            assertNotNull(onError.get());</span>
<span class="nc" id="L338">            assertTrue(onError.get() instanceof SafeSubscriberTestException);</span>
<span class="nc" id="L339">            assertEquals(&quot;failed&quot;, onError.get().getMessage());</span>

            // now assert the exception that was thrown
<span class="nc" id="L342">            RuntimeException onErrorFailedException = (RuntimeException) e;</span>
<span class="nc" id="L343">            assertTrue(onErrorFailedException.getCause() instanceof SafeSubscriberTestException);</span>
<span class="nc" id="L344">            assertEquals(&quot;failure from unsubscribe&quot;, e.getMessage());</span>
<span class="nc" id="L345">        }</span>
<span class="nc" id="L346">    }</span>

    @Test
    @Ignore(&quot;Observers can't throw&quot;)
    public void onErrorFailureWithUnsubscribeFailure() {
<span class="nc" id="L351">        Subscriber&lt;String&gt; subscriber = subscriberOnErrorFail();</span>
        try {
<span class="nc" id="L353">            subscriber.onSubscribe(THROWING_DISPOSABLE);</span>
<span class="nc" id="L354">            new SafeSubscriber&lt;String&gt;(subscriber).onError(new SafeSubscriberTestException(&quot;onError failure&quot;));</span>
<span class="nc" id="L355">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="nc" id="L356">        } catch (Exception e) {</span>
<span class="nc" id="L357">            e.printStackTrace();</span>

            // FIXME no longer assertable
//            assertTrue(o.isUnsubscribed());

            // assertions for what is expected for the actual failure propagated to onError which then fails
<span class="nc" id="L363">            assertTrue(e instanceof RuntimeException);</span>
<span class="nc" id="L364">            assertEquals(&quot;Error occurred when trying to propagate error to Subscriber.onError and during unsubscription.&quot;, e.getMessage());</span>

<span class="nc" id="L366">            Throwable e2 = e.getCause();</span>
<span class="nc" id="L367">            assertTrue(e2 instanceof CompositeException);</span>
<span class="nc" id="L368">            List&lt;Throwable&gt; innerExceptions = ((CompositeException) e2).getExceptions();</span>
<span class="nc" id="L369">            assertEquals(3, innerExceptions.size());</span>

<span class="nc" id="L371">            Throwable e3 = innerExceptions.get(0);</span>
<span class="nc" id="L372">            assertTrue(e3 instanceof SafeSubscriberTestException);</span>
<span class="nc" id="L373">            assertEquals(&quot;onError failure&quot;, e3.getMessage());</span>

<span class="nc" id="L375">            Throwable e4 = innerExceptions.get(1);</span>
<span class="nc" id="L376">            assertTrue(e4 instanceof SafeSubscriberTestException);</span>
<span class="nc" id="L377">            assertEquals(&quot;onErrorFail&quot;, e4.getMessage());</span>

<span class="nc" id="L379">            Throwable e5 = innerExceptions.get(2);</span>
<span class="nc" id="L380">            assertTrue(e5 instanceof SafeSubscriberTestException);</span>
<span class="nc" id="L381">            assertEquals(&quot;failure from unsubscribe&quot;, e5.getMessage());</span>
<span class="nc" id="L382">        }</span>
<span class="nc" id="L383">    }</span>

    @Test
    @Ignore(&quot;Observers can't throw&quot;)
    public void onErrorNotImplementedFailureWithUnsubscribeFailure() {
<span class="nc" id="L388">        Subscriber&lt;String&gt; subscriber = subscriberOnErrorNotImplemented();</span>
        try {
<span class="nc" id="L390">            subscriber.onSubscribe(THROWING_DISPOSABLE);</span>
<span class="nc" id="L391">            new SafeSubscriber&lt;String&gt;(subscriber).onError(new SafeSubscriberTestException(&quot;error!&quot;));</span>
<span class="nc" id="L392">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="nc" id="L393">        } catch (Exception e) {</span>
<span class="nc" id="L394">            e.printStackTrace();</span>

            // FIXME no longer assertable
//            assertTrue(o.isUnsubscribed());

            // assertions for what is expected for the actual failure propagated to onError which then fails
<span class="nc" id="L400">            assertTrue(e instanceof RuntimeException);</span>
<span class="nc" id="L401">            assertEquals(&quot;Subscriber.onError not implemented and error while unsubscribing.&quot;, e.getMessage());</span>

<span class="nc" id="L403">            Throwable e2 = e.getCause();</span>
<span class="nc" id="L404">            assertTrue(e2 instanceof CompositeException);</span>
<span class="nc" id="L405">            List&lt;Throwable&gt; innerExceptions = ((CompositeException) e2).getExceptions();</span>
<span class="nc" id="L406">            assertEquals(2, innerExceptions.size());</span>

<span class="nc" id="L408">            Throwable e3 = innerExceptions.get(0);</span>
<span class="nc" id="L409">            assertTrue(e3 instanceof SafeSubscriberTestException);</span>
<span class="nc" id="L410">            assertEquals(&quot;error!&quot;, e3.getMessage());</span>

<span class="nc" id="L412">            Throwable e4 = innerExceptions.get(1);</span>
<span class="nc" id="L413">            assertTrue(e4 instanceof SafeSubscriberTestException);</span>
<span class="nc" id="L414">            assertEquals(&quot;failure from unsubscribe&quot;, e4.getMessage());</span>
<span class="nc" id="L415">        }</span>
<span class="nc" id="L416">    }</span>

    private static Subscriber&lt;String&gt; subscriberSuccess() {
<span class="nc" id="L419">        return new DefaultSubscriber&lt;String&gt;() {</span>

            @Override
            public void onComplete() {

<span class="nc" id="L424">            }</span>

            @Override
            public void onError(Throwable e) {

<span class="nc" id="L429">            }</span>

            @Override
            public void onNext(String args) {

<span class="nc" id="L434">            }</span>
        };

    }

    private static Subscriber&lt;String&gt; subscriberSuccess(final AtomicReference&lt;Throwable&gt; onError) {
<span class="nc" id="L440">        return new DefaultSubscriber&lt;String&gt;() {</span>

            @Override
            public void onComplete() {

<span class="nc" id="L445">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="nc" id="L449">                onError.set(e);</span>
<span class="nc" id="L450">            }</span>

            @Override
            public void onNext(String args) {

<span class="nc" id="L455">            }</span>
        };

    }

    private static Subscriber&lt;String&gt; OBSERVER_ONNEXT_FAIL(final AtomicReference&lt;Throwable&gt; onError) {
<span class="fc" id="L461">        return new DefaultSubscriber&lt;String&gt;() {</span>

            @Override
            public void onComplete() {

<span class="nc" id="L466">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="fc" id="L470">                onError.set(e);</span>
<span class="fc" id="L471">            }</span>

            @Override
            public void onNext(String args) {
<span class="fc" id="L475">                throw new SafeSubscriberTestException(&quot;onNextFail&quot;);</span>
            }
        };

    }

    private static Subscriber&lt;String&gt; OBSERVER_ONNEXT_ONERROR_FAIL() {
<span class="fc" id="L482">        return new DefaultSubscriber&lt;String&gt;() {</span>

            @Override
            public void onComplete() {

<span class="nc" id="L487">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="nc" id="L491">                throw new SafeSubscriberTestException(&quot;onErrorFail&quot;);</span>
            }

            @Override
            public void onNext(String args) {
<span class="fc" id="L496">                throw new SafeSubscriberTestException(&quot;onNextFail&quot;);</span>
            }

        };
    }

    private static Subscriber&lt;String&gt; subscriberOnErrorFail() {
<span class="fc" id="L503">        return new DefaultSubscriber&lt;String&gt;() {</span>

            @Override
            public void onComplete() {

<span class="nc" id="L508">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="fc" id="L512">                throw new SafeSubscriberTestException(&quot;onErrorFail&quot;);</span>
            }

            @Override
            public void onNext(String args) {

<span class="nc" id="L518">            }</span>

        };
    }

    private static Subscriber&lt;String&gt; subscriberOnErrorNotImplemented() {
<span class="nc" id="L524">        return new DefaultSubscriber&lt;String&gt;() {</span>

            @Override
            public void onComplete() {

<span class="nc" id="L529">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="nc" id="L533">                throw new RuntimeException(e);</span>
//                throw new OnErrorNotImplementedException(e);
            }

            @Override
            public void onNext(String args) {

<span class="nc" id="L540">            }</span>

        };
    }

    private static Subscriber&lt;String&gt; OBSERVER_ONCOMPLETED_FAIL(final AtomicReference&lt;Throwable&gt; onError) {
<span class="fc" id="L546">        return new DefaultSubscriber&lt;String&gt;() {</span>

            @Override
            public void onComplete() {
<span class="fc" id="L550">                throw new SafeSubscriberTestException(&quot;onCompleteFail&quot;);</span>
            }

            @Override
            public void onError(Throwable e) {
<span class="nc" id="L555">                onError.set(e);</span>
<span class="nc" id="L556">            }</span>

            @Override
            public void onNext(String args) {

<span class="nc" id="L561">            }</span>

        };
    }

    @SuppressWarnings(&quot;serial&quot;)
    private static class SafeSubscriberTestException extends RuntimeException {
        SafeSubscriberTestException(String message) {
<span class="fc" id="L569">            super(message);</span>
<span class="fc" id="L570">        }</span>
    }

    @Test
    @Ignore(&quot;Observers can't throw&quot;)
    public void testOnCompletedThrows() {
<span class="nc" id="L576">        final AtomicReference&lt;Throwable&gt; error = new AtomicReference&lt;Throwable&gt;();</span>
<span class="nc" id="L577">        SafeSubscriber&lt;Integer&gt; s = new SafeSubscriber&lt;Integer&gt;(new DefaultSubscriber&lt;Integer&gt;() {</span>
            @Override
            public void onNext(Integer t) {

<span class="nc" id="L581">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="nc" id="L585">                error.set(e);</span>
<span class="nc" id="L586">            }</span>

            @Override
            public void onComplete() {
<span class="nc" id="L590">                throw new TestException();</span>
            }
        });

        try {
<span class="nc" id="L595">            s.onComplete();</span>
<span class="nc" id="L596">            Assert.fail();</span>
<span class="nc" id="L597">        } catch (RuntimeException e) {</span>
<span class="nc" id="L598">           assertNull(error.get());</span>
<span class="nc" id="L599">        }</span>
<span class="nc" id="L600">    }</span>

    @Test
    public void testActual() {
<span class="fc" id="L604">        Subscriber&lt;Integer&gt; actual = new DefaultSubscriber&lt;Integer&gt;() {</span>
            @Override
            public void onNext(Integer t) {
<span class="nc" id="L607">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="nc" id="L611">            }</span>

            @Override
            public void onComplete() {
<span class="nc" id="L615">            }</span>
        };
<span class="fc" id="L617">        SafeSubscriber&lt;Integer&gt; s = new SafeSubscriber&lt;Integer&gt;(actual);</span>

<span class="fc" id="L619">        assertSame(actual, s.downstream);</span>
<span class="fc" id="L620">    }</span>

    @Test
    public void dispose() {
<span class="fc" id="L624">        TestSubscriber&lt;Integer&gt; ts = new TestSubscriber&lt;Integer&gt;();</span>

<span class="fc" id="L626">        SafeSubscriber&lt;Integer&gt; so = new SafeSubscriber&lt;Integer&gt;(ts);</span>

<span class="fc" id="L628">        BooleanSubscription bs = new BooleanSubscription();</span>

<span class="fc" id="L630">        so.onSubscribe(bs);</span>

<span class="fc" id="L632">        ts.dispose();</span>

<span class="fc" id="L634">        assertTrue(bs.isCancelled());</span>

//        assertTrue(so.isDisposed());
<span class="fc" id="L637">    }</span>

    @Test
    public void onNextAfterComplete() {
<span class="fc" id="L641">        TestSubscriber&lt;Integer&gt; ts = new TestSubscriber&lt;Integer&gt;();</span>

<span class="fc" id="L643">        SafeSubscriber&lt;Integer&gt; so = new SafeSubscriber&lt;Integer&gt;(ts);</span>

<span class="fc" id="L645">        BooleanSubscription bs = new BooleanSubscription();</span>

<span class="fc" id="L647">        so.onSubscribe(bs);</span>

<span class="fc" id="L649">        so.onComplete();</span>

<span class="fc" id="L651">        so.onNext(1);</span>

<span class="fc" id="L653">        so.onError(new TestException());</span>

<span class="fc" id="L655">        so.onComplete();</span>

<span class="fc" id="L657">        ts.assertResult();</span>
<span class="fc" id="L658">    }</span>

    @Test
    public void onNextNull() {
<span class="fc" id="L662">        TestSubscriber&lt;Integer&gt; ts = new TestSubscriber&lt;Integer&gt;();</span>

<span class="fc" id="L664">        SafeSubscriber&lt;Integer&gt; so = new SafeSubscriber&lt;Integer&gt;(ts);</span>

<span class="fc" id="L666">        BooleanSubscription bs = new BooleanSubscription();</span>

<span class="fc" id="L668">        so.onSubscribe(bs);</span>

<span class="fc" id="L670">        so.onNext(null);</span>

<span class="fc" id="L672">        ts.assertFailure(NullPointerException.class);</span>
<span class="fc" id="L673">    }</span>

    @Test
    public void onNextWithoutOnSubscribe() {
<span class="fc" id="L677">        TestSubscriber&lt;Integer&gt; ts = new TestSubscriber&lt;Integer&gt;();</span>

<span class="fc" id="L679">        SafeSubscriber&lt;Integer&gt; so = new SafeSubscriber&lt;Integer&gt;(ts);</span>

<span class="fc" id="L681">        so.onNext(1);</span>

<span class="fc" id="L683">        ts.assertFailureAndMessage(NullPointerException.class, &quot;Subscription not set!&quot;);</span>
<span class="fc" id="L684">    }</span>

    @Test
    public void onErrorWithoutOnSubscribe() {
<span class="fc" id="L688">        TestSubscriber&lt;Integer&gt; ts = new TestSubscriber&lt;Integer&gt;();</span>

<span class="fc" id="L690">        SafeSubscriber&lt;Integer&gt; so = new SafeSubscriber&lt;Integer&gt;(ts);</span>

<span class="fc" id="L692">        so.onError(new TestException());</span>

<span class="fc" id="L694">        ts.assertFailure(CompositeException.class);</span>

<span class="fc" id="L696">        TestHelper.assertError(ts, 0, TestException.class);</span>
<span class="fc" id="L697">        TestHelper.assertError(ts, 1, NullPointerException.class, &quot;Subscription not set!&quot;);</span>
<span class="fc" id="L698">    }</span>

    @Test
    public void onCompleteWithoutOnSubscribe() {
<span class="fc" id="L702">        TestSubscriber&lt;Integer&gt; ts = new TestSubscriber&lt;Integer&gt;();</span>

<span class="fc" id="L704">        SafeSubscriber&lt;Integer&gt; so = new SafeSubscriber&lt;Integer&gt;(ts);</span>

<span class="fc" id="L706">        so.onComplete();</span>

<span class="fc" id="L708">        ts.assertFailureAndMessage(NullPointerException.class, &quot;Subscription not set!&quot;);</span>
<span class="fc" id="L709">    }</span>

    @Test
    public void onNextNormal() {
<span class="fc" id="L713">        TestSubscriber&lt;Integer&gt; ts = new TestSubscriber&lt;Integer&gt;();</span>

<span class="fc" id="L715">        SafeSubscriber&lt;Integer&gt; so = new SafeSubscriber&lt;Integer&gt;(ts);</span>

<span class="fc" id="L717">        BooleanSubscription bs = new BooleanSubscription();</span>

<span class="fc" id="L719">        so.onSubscribe(bs);</span>

<span class="fc" id="L721">        so.onNext(1);</span>
<span class="fc" id="L722">        so.onComplete();</span>

<span class="fc" id="L724">        ts.assertResult(1);</span>
<span class="fc" id="L725">    }</span>

    static final class CrashDummy implements FlowableSubscriber&lt;Object&gt;, Subscription {
        final boolean crashOnSubscribe;

        int crashOnNext;

        final boolean crashOnError;

        final boolean crashOnComplete;

        final boolean crashDispose;

        final boolean crashRequest;

        Throwable error;

        CrashDummy(boolean crashOnSubscribe, int crashOnNext,
<span class="fc" id="L743">                boolean crashOnError, boolean crashOnComplete, boolean crashDispose, boolean crashRequest) {</span>
<span class="fc" id="L744">            this.crashOnSubscribe = crashOnSubscribe;</span>
<span class="fc" id="L745">            this.crashOnNext = crashOnNext;</span>
<span class="fc" id="L746">            this.crashOnError = crashOnError;</span>
<span class="fc" id="L747">            this.crashOnComplete = crashOnComplete;</span>
<span class="fc" id="L748">            this.crashDispose = crashDispose;</span>
<span class="fc" id="L749">            this.crashRequest = crashRequest;</span>
<span class="fc" id="L750">        }</span>

        @Override
        public void cancel() {
<span class="fc bfc" id="L754" title="All 2 branches covered.">            if (crashDispose) {</span>
<span class="fc" id="L755">                throw new TestException(&quot;cancel()&quot;);</span>
            }
<span class="fc" id="L757">        }</span>

        @Override
        public void request(long n) {
<span class="pc bpc" id="L761" title="1 of 2 branches missed.">            if (crashRequest) {</span>
<span class="fc" id="L762">                throw new TestException(&quot;request()&quot;);</span>
            }
<span class="nc" id="L764">        }</span>

        @Override
        public void onSubscribe(Subscription s) {
<span class="fc bfc" id="L768" title="All 2 branches covered.">            if (crashOnSubscribe) {</span>
<span class="fc" id="L769">                throw new TestException(&quot;onSubscribe()&quot;);</span>
            }
<span class="fc" id="L771">        }</span>

        @Override
        public void onNext(Object value) {
<span class="pc bpc" id="L775" title="1 of 2 branches missed.">            if (--crashOnNext == 0) {</span>
<span class="fc" id="L776">                throw new TestException(&quot;onNext(&quot; + value + &quot;)&quot;);</span>
            }
<span class="nc" id="L778">        }</span>

        @Override
        public void onError(Throwable e) {
<span class="fc bfc" id="L782" title="All 2 branches covered.">            if (crashOnError) {</span>
<span class="fc" id="L783">                throw new TestException(&quot;onError(&quot; + e + &quot;)&quot;);</span>
            }
<span class="fc" id="L785">            error = e;</span>
<span class="fc" id="L786">        }</span>

        @Override
        public void onComplete() {
<span class="pc bpc" id="L790" title="1 of 2 branches missed.">            if (crashOnComplete) {</span>
<span class="fc" id="L791">                throw new TestException(&quot;onComplete()&quot;);</span>
            }
<span class="nc" id="L793">        }</span>

        public SafeSubscriber&lt;Object&gt; toSafe() {
<span class="fc" id="L796">            return new SafeSubscriber&lt;Object&gt;(this);</span>
        }

        public CrashDummy assertError(Class&lt;? extends Throwable&gt; clazz) {
<span class="pc bpc" id="L800" title="1 of 2 branches missed.">            if (!clazz.isInstance(error)) {</span>
<span class="nc" id="L801">                throw new AssertionError(&quot;Different error: &quot; + error);</span>
            }
<span class="fc" id="L803">            return this;</span>
        }

        public CrashDummy assertInnerError(int index, Class&lt;? extends Throwable&gt; clazz) {
<span class="fc" id="L807">            List&lt;Throwable&gt; cel = TestHelper.compositeList(error);</span>
<span class="fc" id="L808">            TestHelper.assertError(cel, index, clazz);</span>
<span class="fc" id="L809">            return this;</span>
        }

        public CrashDummy assertInnerError(int index, Class&lt;? extends Throwable&gt; clazz, String message) {
<span class="fc" id="L813">            List&lt;Throwable&gt; cel = TestHelper.compositeList(error);</span>
<span class="fc" id="L814">            TestHelper.assertError(cel, index, clazz, message);</span>
<span class="fc" id="L815">            return this;</span>
        }

    }

    @Test
    public void onNextOnErrorCrash() {
<span class="fc" id="L822">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L825">            CrashDummy cd = new CrashDummy(false, 1, true, false, false, false);</span>
<span class="fc" id="L826">            SafeSubscriber&lt;Object&gt; so = cd.toSafe();</span>
<span class="fc" id="L827">            so.onSubscribe(cd);</span>

<span class="fc" id="L829">            so.onNext(1);</span>

<span class="fc" id="L831">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L832">            List&lt;Throwable&gt; ce = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L833">            TestHelper.assertError(ce, 0, TestException.class, &quot;onNext(1)&quot;);</span>
<span class="fc" id="L834">            TestHelper.assertError(ce, 1, TestException.class, &quot;onError(io.reactivex.exceptions.TestException: onNext(1))&quot;);</span>
        } finally {
<span class="fc" id="L836">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L838">    }</span>

    @Test
    public void onNextDisposeCrash() {
<span class="fc" id="L842">        CrashDummy cd = new CrashDummy(false, 1, false, false, true, false);</span>
<span class="fc" id="L843">        SafeSubscriber&lt;Object&gt; so = cd.toSafe();</span>
<span class="fc" id="L844">        so.onSubscribe(cd);</span>

<span class="fc" id="L846">        so.onNext(1);</span>

<span class="fc" id="L848">        cd.assertError(CompositeException.class);</span>
<span class="fc" id="L849">        cd.assertInnerError(0, TestException.class, &quot;onNext(1)&quot;);</span>
<span class="fc" id="L850">        cd.assertInnerError(1, TestException.class, &quot;cancel()&quot;);</span>
<span class="fc" id="L851">    }</span>

    @Test
    public void onSubscribeTwice() {
<span class="fc" id="L855">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L858">            CrashDummy cd = new CrashDummy(false, 1, false, false, false, false);</span>
<span class="fc" id="L859">            SafeSubscriber&lt;Object&gt; so = cd.toSafe();</span>
<span class="fc" id="L860">            so.onSubscribe(cd);</span>
<span class="fc" id="L861">            so.onSubscribe(cd);</span>

<span class="fc" id="L863">            TestHelper.assertError(list, 0, IllegalStateException.class);</span>
        } finally {
<span class="fc" id="L865">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L867">    }</span>

    @Test
    public void onSubscribeCrashes() {
<span class="fc" id="L871">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L874">            CrashDummy cd = new CrashDummy(true, 1, false, false, false, false);</span>
<span class="fc" id="L875">            SafeSubscriber&lt;Object&gt; so = cd.toSafe();</span>
<span class="fc" id="L876">            so.onSubscribe(cd);</span>

<span class="fc" id="L878">            TestHelper.assertUndeliverable(list, 0, TestException.class, &quot;onSubscribe()&quot;);</span>
        } finally {
<span class="fc" id="L880">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L882">    }</span>

    @Test
    public void onSubscribeAndDisposeCrashes() {
<span class="fc" id="L886">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L889">            CrashDummy cd = new CrashDummy(true, 1, false, false, true, false);</span>
<span class="fc" id="L890">            SafeSubscriber&lt;Object&gt; so = cd.toSafe();</span>
<span class="fc" id="L891">            so.onSubscribe(cd);</span>

<span class="fc" id="L893">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L894">            List&lt;Throwable&gt; ce = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L895">            TestHelper.assertError(ce, 0, TestException.class, &quot;onSubscribe()&quot;);</span>
<span class="fc" id="L896">            TestHelper.assertError(ce, 1, TestException.class, &quot;cancel()&quot;);</span>
        } finally {
<span class="fc" id="L898">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L900">    }</span>

    @Test
    public void onNextOnSubscribeCrash() {
<span class="fc" id="L904">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L907">            CrashDummy cd = new CrashDummy(true, 1, false, false, false, false);</span>
<span class="fc" id="L908">            SafeSubscriber&lt;Object&gt; so = cd.toSafe();</span>

<span class="fc" id="L910">            so.onNext(1);</span>

<span class="fc" id="L912">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L913">            List&lt;Throwable&gt; ce = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L914">            TestHelper.assertError(ce, 0, NullPointerException.class, &quot;Subscription not set!&quot;);</span>
<span class="fc" id="L915">            TestHelper.assertError(ce, 1, TestException.class, &quot;onSubscribe()&quot;);</span>
        } finally {
<span class="fc" id="L917">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L919">    }</span>

    @Test
    public void onNextNullDisposeCrashes() {
<span class="fc" id="L923">        CrashDummy cd = new CrashDummy(false, 1, false, false, true, false);</span>
<span class="fc" id="L924">        SafeSubscriber&lt;Object&gt; so = cd.toSafe();</span>
<span class="fc" id="L925">        so.onSubscribe(cd);</span>

<span class="fc" id="L927">        so.onNext(null);</span>

<span class="fc" id="L929">        cd.assertInnerError(0, NullPointerException.class);</span>
<span class="fc" id="L930">        cd.assertInnerError(1, TestException.class, &quot;cancel()&quot;);</span>
<span class="fc" id="L931">    }</span>

    @Test
    public void noSubscribeOnErrorCrashes() {
<span class="fc" id="L935">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L938">            CrashDummy cd = new CrashDummy(false, 1, true, false, false, false);</span>
<span class="fc" id="L939">            SafeSubscriber&lt;Object&gt; so = cd.toSafe();</span>

<span class="fc" id="L941">            so.onNext(1);</span>

<span class="fc" id="L943">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L944">            List&lt;Throwable&gt; ce = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L945">            TestHelper.assertError(ce, 0, NullPointerException.class, &quot;Subscription not set!&quot;);</span>
<span class="fc" id="L946">            TestHelper.assertError(ce, 1, TestException.class, &quot;onError(java.lang.NullPointerException: Subscription not set!)&quot;);</span>
        } finally {
<span class="fc" id="L948">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L950">    }</span>

    @Test
    public void onErrorNull() {
<span class="fc" id="L954">        CrashDummy cd = new CrashDummy(false, 1, false, false, false, false);</span>
<span class="fc" id="L955">        SafeSubscriber&lt;Object&gt; so = cd.toSafe();</span>
<span class="fc" id="L956">        so.onSubscribe(cd);</span>

<span class="fc" id="L958">        so.onError(null);</span>

<span class="fc" id="L960">        cd.assertError(NullPointerException.class);</span>
<span class="fc" id="L961">    }</span>

    @Test
    public void onErrorNoSubscribeCrash() {
<span class="fc" id="L965">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L968">            CrashDummy cd = new CrashDummy(true, 1, false, false, false, false);</span>
<span class="fc" id="L969">            SafeSubscriber&lt;Object&gt; so = cd.toSafe();</span>

<span class="fc" id="L971">            so.onError(new TestException());</span>

<span class="fc" id="L973">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L974">            List&lt;Throwable&gt; ce = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L975">            TestHelper.assertError(ce, 0, TestException.class);</span>
<span class="fc" id="L976">            TestHelper.assertError(ce, 1, NullPointerException.class, &quot;Subscription not set!&quot;);</span>
        } finally {
<span class="fc" id="L978">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L980">    }</span>

    @Test
    public void onErrorNoSubscribeOnErrorCrash() {
<span class="fc" id="L984">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L987">            CrashDummy cd = new CrashDummy(false, 1, true, false, false, false);</span>
<span class="fc" id="L988">            SafeSubscriber&lt;Object&gt; so = cd.toSafe();</span>

<span class="fc" id="L990">            so.onError(new TestException());</span>

<span class="fc" id="L992">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L993">            List&lt;Throwable&gt; ce = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L994">            TestHelper.assertError(ce, 0, TestException.class);</span>
<span class="fc" id="L995">            TestHelper.assertError(ce, 1, NullPointerException.class, &quot;Subscription not set!&quot;);</span>
<span class="fc" id="L996">            TestHelper.assertError(ce, 2, TestException.class);</span>
        } finally {
<span class="fc" id="L998">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L1000">    }</span>

    @Test
    public void onCompleteteCrash() {
<span class="fc" id="L1004">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L1007">            CrashDummy cd = new CrashDummy(false, 1, false, true, false, false);</span>
<span class="fc" id="L1008">            SafeSubscriber&lt;Object&gt; so = cd.toSafe();</span>

<span class="fc" id="L1010">            so.onSubscribe(cd);</span>

<span class="fc" id="L1012">            so.onComplete();</span>

<span class="fc" id="L1014">            TestHelper.assertUndeliverable(list, 0, TestException.class, &quot;onComplete()&quot;);</span>
        } finally {
<span class="fc" id="L1016">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L1018">    }</span>

    @Test
    public void onCompleteteNoSubscribeCrash() {
<span class="fc" id="L1022">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L1025">            CrashDummy cd = new CrashDummy(true, 1, false, true, false, false);</span>
<span class="fc" id="L1026">            SafeSubscriber&lt;Object&gt; so = cd.toSafe();</span>

<span class="fc" id="L1028">            so.onComplete();</span>

<span class="fc" id="L1030">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L1031">            List&lt;Throwable&gt; ce = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L1032">            TestHelper.assertError(ce, 0, NullPointerException.class, &quot;Subscription not set!&quot;);</span>
<span class="fc" id="L1033">            TestHelper.assertError(ce, 1, TestException.class, &quot;onSubscribe()&quot;);</span>
        } finally {
<span class="fc" id="L1035">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L1037">    }</span>

    @Test
    public void onCompleteteNoSubscribeOnErrorCrash() {
<span class="fc" id="L1041">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L1044">            CrashDummy cd = new CrashDummy(false, 1, true, true, false, false);</span>
<span class="fc" id="L1045">            SafeSubscriber&lt;Object&gt; so = cd.toSafe();</span>

<span class="fc" id="L1047">            so.onComplete();</span>

<span class="fc" id="L1049">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L1050">            List&lt;Throwable&gt; ce = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L1051">            TestHelper.assertError(ce, 0, NullPointerException.class, &quot;Subscription not set!&quot;);</span>
<span class="fc" id="L1052">            TestHelper.assertError(ce, 1, TestException.class);</span>
        } finally {
<span class="fc" id="L1054">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L1056">    }</span>

    @Test
    public void requestCrash() {
<span class="fc" id="L1060">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L1063">            CrashDummy cd = new CrashDummy(false, 1, false, false, false, true);</span>
<span class="fc" id="L1064">            SafeSubscriber&lt;Object&gt; so = cd.toSafe();</span>
<span class="fc" id="L1065">            so.onSubscribe(cd);</span>

<span class="fc" id="L1067">            so.request(1);</span>

<span class="fc" id="L1069">            TestHelper.assertUndeliverable(list, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L1071">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L1073">    }</span>

    @Test
    public void cancelCrash() {
<span class="fc" id="L1077">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L1080">            CrashDummy cd = new CrashDummy(false, 1, false, false, true, false);</span>
<span class="fc" id="L1081">            SafeSubscriber&lt;Object&gt; so = cd.toSafe();</span>
<span class="fc" id="L1082">            so.onSubscribe(cd);</span>

<span class="fc" id="L1084">            so.cancel();</span>

<span class="fc" id="L1086">            TestHelper.assertUndeliverable(list, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L1088">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L1090">    }</span>

    @Test
    public void requestCancelCrash() {
<span class="fc" id="L1094">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L1097">            CrashDummy cd = new CrashDummy(false, 1, false, false, true, true);</span>
<span class="fc" id="L1098">            SafeSubscriber&lt;Object&gt; so = cd.toSafe();</span>
<span class="fc" id="L1099">            so.onSubscribe(cd);</span>

<span class="fc" id="L1101">            so.request(1);</span>

<span class="fc" id="L1103">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L1104">            List&lt;Throwable&gt; ce = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L1105">           TestHelper.assertError(ce, 0, TestException.class, &quot;request()&quot;);</span>
<span class="fc" id="L1106">            TestHelper.assertError(ce, 1, TestException.class, &quot;cancel()&quot;);</span>
        } finally {
<span class="fc" id="L1108">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L1110">    }</span>

}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>