<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>CompletableUsingTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.operators.completable</a> &gt; <span class="el_source">CompletableUsingTest.java</span></div><h1>CompletableUsingTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.operators.completable;

import static org.junit.Assert.*;

import java.util.List;
import java.util.concurrent.Callable;

import org.junit.Test;

import io.reactivex.*;
import io.reactivex.disposables.*;
import io.reactivex.exceptions.*;
import io.reactivex.functions.*;
import io.reactivex.internal.functions.Functions;
import io.reactivex.observers.TestObserver;
import io.reactivex.plugins.RxJavaPlugins;
import io.reactivex.subjects.PublishSubject;

<span class="fc" id="L32">public class CompletableUsingTest {</span>

    @Test
    public void resourceSupplierThrows() {

<span class="fc" id="L37">        Completable.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L40">                throw new TestException();</span>
            }
<span class="fc" id="L42">        }, new Function&lt;Object, CompletableSource&gt;() {</span>
            @Override
            public CompletableSource apply(Object v) throws Exception {
<span class="nc" id="L45">                return Completable.complete();</span>
            }
<span class="fc" id="L47">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {

<span class="nc" id="L51">            }</span>
        })
<span class="fc" id="L53">        .test()</span>
<span class="fc" id="L54">        .assertFailure(TestException.class);</span>
<span class="fc" id="L55">    }</span>

    @Test
    public void errorEager() {

<span class="fc" id="L60">        Completable.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L63">                return 1;</span>
            }
<span class="fc" id="L65">        }, new Function&lt;Object, CompletableSource&gt;() {</span>
            @Override
            public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L68">                return Completable.error(new TestException());</span>
            }
<span class="fc" id="L70">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {

<span class="fc" id="L74">            }</span>
        }, true)
<span class="fc" id="L76">        .test()</span>
<span class="fc" id="L77">        .assertFailure(TestException.class);</span>
<span class="fc" id="L78">    }</span>

    @Test
    public void emptyEager() {

<span class="fc" id="L83">        Completable.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L86">                return 1;</span>
            }
<span class="fc" id="L88">        }, new Function&lt;Object, CompletableSource&gt;() {</span>
            @Override
            public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L91">                return Completable.complete();</span>
            }
<span class="fc" id="L93">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {

<span class="fc" id="L97">            }</span>
        }, true)
<span class="fc" id="L99">        .test()</span>
<span class="fc" id="L100">        .assertResult();</span>
<span class="fc" id="L101">    }</span>

    @Test
    public void errorNonEager() {

<span class="fc" id="L106">        Completable.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L109">                return 1;</span>
            }
<span class="fc" id="L111">        }, new Function&lt;Object, CompletableSource&gt;() {</span>
            @Override
            public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L114">                return Completable.error(new TestException());</span>
            }
<span class="fc" id="L116">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {

<span class="fc" id="L120">            }</span>
        }, false)
<span class="fc" id="L122">        .test()</span>
<span class="fc" id="L123">        .assertFailure(TestException.class);</span>
<span class="fc" id="L124">    }</span>

    @Test
    public void emptyNonEager() {

<span class="fc" id="L129">        Completable.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L132">                return 1;</span>
            }
<span class="fc" id="L134">        }, new Function&lt;Object, CompletableSource&gt;() {</span>
            @Override
            public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L137">                return Completable.complete();</span>
            }
<span class="fc" id="L139">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {

<span class="fc" id="L143">            }</span>
        }, false)
<span class="fc" id="L145">        .test()</span>
<span class="fc" id="L146">        .assertResult();</span>
<span class="fc" id="L147">    }</span>

    @Test
    public void supplierCrashEager() {

<span class="fc" id="L152">        Completable.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L155">                return 1;</span>
            }
<span class="fc" id="L157">        }, new Function&lt;Object, CompletableSource&gt;() {</span>
            @Override
            public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L160">                throw new TestException();</span>
            }
<span class="fc" id="L162">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {

<span class="fc" id="L166">            }</span>
        }, true)
<span class="fc" id="L168">        .test()</span>
<span class="fc" id="L169">        .assertFailure(TestException.class);</span>
<span class="fc" id="L170">    }</span>

    @Test
    public void supplierCrashNonEager() {

<span class="fc" id="L175">        Completable.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L178">                return 1;</span>
            }
<span class="fc" id="L180">        }, new Function&lt;Object, CompletableSource&gt;() {</span>
            @Override
            public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L183">                throw new TestException();</span>
            }
<span class="fc" id="L185">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {

<span class="fc" id="L189">            }</span>
        }, false)
<span class="fc" id="L191">        .test()</span>
<span class="fc" id="L192">        .assertFailure(TestException.class);</span>
<span class="fc" id="L193">    }</span>

    @Test
    public void supplierAndDisposerCrashEager() {
<span class="fc" id="L197">        TestObserver&lt;Void&gt; to = Completable.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L200">                return 1;</span>
            }
<span class="fc" id="L202">        }, new Function&lt;Object, CompletableSource&gt;() {</span>
            @Override
            public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L205">                throw new TestException(&quot;Main&quot;);</span>
            }
<span class="fc" id="L207">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {
<span class="fc" id="L210">                throw new TestException(&quot;Disposer&quot;);</span>
            }
        }, true)
<span class="fc" id="L213">        .test()</span>
<span class="fc" id="L214">        .assertFailure(CompositeException.class);</span>

<span class="fc" id="L216">        List&lt;Throwable&gt; list = TestHelper.compositeList(to.errors().get(0));</span>

<span class="fc" id="L218">        TestHelper.assertError(list, 0, TestException.class, &quot;Main&quot;);</span>
<span class="fc" id="L219">        TestHelper.assertError(list, 1, TestException.class, &quot;Disposer&quot;);</span>
<span class="fc" id="L220">    }</span>

    @Test
    public void supplierAndDisposerCrashNonEager() {
<span class="fc" id="L224">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L226">            Completable.using(new Callable&lt;Object&gt;() {</span>
                @Override
                public Object call() throws Exception {
<span class="fc" id="L229">                    return 1;</span>
                }
<span class="fc" id="L231">            }, new Function&lt;Object, CompletableSource&gt;() {</span>
                @Override
                public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L234">                    throw new TestException(&quot;Main&quot;);</span>
                }
<span class="fc" id="L236">            }, new Consumer&lt;Object&gt;() {</span>
                @Override
                public void accept(Object d) throws Exception {
<span class="fc" id="L239">                    throw new TestException(&quot;Disposer&quot;);</span>
                }
            }, false)
<span class="fc" id="L242">            .test()</span>
<span class="fc" id="L243">            .assertFailureAndMessage(TestException.class, &quot;Main&quot;);</span>

<span class="fc" id="L245">            TestHelper.assertUndeliverable(errors, 0, TestException.class, &quot;Disposer&quot;);</span>
        } finally {
<span class="fc" id="L247">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L249">    }</span>

    @Test
    public void dispose() {
<span class="fc" id="L253">        final int[] call = {0 };</span>

<span class="fc" id="L255">        TestObserver&lt;Void&gt; to = Completable.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L258">                return 1;</span>
            }
<span class="fc" id="L260">        }, new Function&lt;Object, CompletableSource&gt;() {</span>
            @Override
            public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L263">                return Completable.never();</span>
            }
<span class="fc" id="L265">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {
<span class="fc" id="L268">                call[0]++;</span>
<span class="fc" id="L269">            }</span>
        }, false)
<span class="fc" id="L271">        .test();</span>

<span class="fc" id="L273">        to.cancel();</span>

<span class="fc" id="L275">        assertEquals(1, call[0]);</span>
<span class="fc" id="L276">    }</span>

    @Test
    public void disposeCrashes() {
<span class="fc" id="L280">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L282">            TestObserver&lt;Void&gt; to = Completable.using(new Callable&lt;Object&gt;() {</span>
                @Override
                public Object call() throws Exception {
<span class="fc" id="L285">                    return 1;</span>
                }
<span class="fc" id="L287">            }, new Function&lt;Object, CompletableSource&gt;() {</span>
                @Override
                public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L290">                    return Completable.never();</span>
                }
<span class="fc" id="L292">            }, new Consumer&lt;Object&gt;() {</span>
                @Override
                public void accept(Object d) throws Exception {
<span class="fc" id="L295">                    throw new TestException();</span>
                }
            }, false)
<span class="fc" id="L298">            .test();</span>

<span class="fc" id="L300">            to.cancel();</span>

<span class="fc" id="L302">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L304">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L306">    }</span>

    @Test
    public void isDisposed() {
<span class="fc" id="L310">        TestHelper.checkDisposed(Completable.using(new Callable&lt;Object&gt;() {</span>
                @Override
                public Object call() throws Exception {
<span class="fc" id="L313">                    return 1;</span>
                }
<span class="fc" id="L315">            }, new Function&lt;Object, CompletableSource&gt;() {</span>
                @Override
                public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L318">                    return Completable.never();</span>
                }
<span class="fc" id="L320">            }, new Consumer&lt;Object&gt;() {</span>
                @Override
                public void accept(Object d) throws Exception {

<span class="fc" id="L324">                }</span>
            }, false));
<span class="fc" id="L326">    }</span>

    @Test
    public void justDisposerCrashes() {
<span class="fc" id="L330">        Completable.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L333">                return 1;</span>
            }
<span class="fc" id="L335">        }, new Function&lt;Object, CompletableSource&gt;() {</span>
            @Override
            public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L338">                return Completable.complete();</span>
            }
<span class="fc" id="L340">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {
<span class="fc" id="L343">                throw new TestException(&quot;Disposer&quot;);</span>
            }
        }, true)
<span class="fc" id="L346">        .test()</span>
<span class="fc" id="L347">        .assertFailure(TestException.class);</span>
<span class="fc" id="L348">    }</span>

    @Test
    public void emptyDisposerCrashes() {
<span class="fc" id="L352">        Completable.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L355">                return 1;</span>
            }
<span class="fc" id="L357">        }, new Function&lt;Object, CompletableSource&gt;() {</span>
            @Override
            public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L360">                return Completable.complete();</span>
            }
<span class="fc" id="L362">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {
<span class="fc" id="L365">                throw new TestException(&quot;Disposer&quot;);</span>
            }
        }, true)
<span class="fc" id="L368">        .test()</span>
<span class="fc" id="L369">        .assertFailure(TestException.class);</span>
<span class="fc" id="L370">    }</span>

    @Test
    public void errorDisposerCrash() {
<span class="fc" id="L374">        TestObserver&lt;Void&gt; to = Completable.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L377">                return 1;</span>
            }
<span class="fc" id="L379">        }, new Function&lt;Object, CompletableSource&gt;() {</span>
            @Override
            public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L382">                return Completable.error(new TestException(&quot;Main&quot;));</span>
            }
<span class="fc" id="L384">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {
<span class="fc" id="L387">                throw new TestException(&quot;Disposer&quot;);</span>
            }
        }, true)
<span class="fc" id="L390">        .test()</span>
<span class="fc" id="L391">        .assertFailure(CompositeException.class);</span>

<span class="fc" id="L393">        List&lt;Throwable&gt; list = TestHelper.compositeList(to.errors().get(0));</span>

<span class="fc" id="L395">        TestHelper.assertError(list, 0, TestException.class, &quot;Main&quot;);</span>
<span class="fc" id="L396">        TestHelper.assertError(list, 1, TestException.class, &quot;Disposer&quot;);</span>
<span class="fc" id="L397">    }</span>

    @Test
    public void doubleOnSubscribe() {
<span class="fc" id="L401">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L403">            Completable.using(new Callable&lt;Object&gt;() {</span>
                @Override
                public Object call() throws Exception {
<span class="fc" id="L406">                    return 1;</span>
                }
<span class="fc" id="L408">            }, new Function&lt;Object, CompletableSource&gt;() {</span>
                @Override
                public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L411">                    return Completable.wrap(new CompletableSource() {</span>
                        @Override
                        public void subscribe(CompletableObserver observer) {
<span class="fc" id="L414">                            Disposable d1 = Disposables.empty();</span>

<span class="fc" id="L416">                            observer.onSubscribe(d1);</span>

<span class="fc" id="L418">                            Disposable d2 = Disposables.empty();</span>

<span class="fc" id="L420">                            observer.onSubscribe(d2);</span>

<span class="fc" id="L422">                            assertFalse(d1.isDisposed());</span>

<span class="fc" id="L424">                            assertTrue(d2.isDisposed());</span>
<span class="fc" id="L425">                        }</span>
                    });
                }
<span class="fc" id="L428">            }, new Consumer&lt;Object&gt;() {</span>
                @Override
                public void accept(Object d) throws Exception {

<span class="nc" id="L432">                }</span>
<span class="fc" id="L433">            }, false).test();</span>
<span class="fc" id="L434">            TestHelper.assertError(errors, 0, IllegalStateException.class, &quot;Disposable already set!&quot;);</span>
        } finally {
<span class="fc" id="L436">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L438">    }</span>

    @Test
    public void successDisposeRace() {
<span class="fc bfc" id="L442" title="All 2 branches covered.">        for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>

<span class="fc" id="L444">            final PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L446">            final TestObserver&lt;Void&gt; to = Completable.using(new Callable&lt;Object&gt;() {</span>
                @Override
                public Object call() throws Exception {
<span class="fc" id="L449">                    return 1;</span>
                }
<span class="fc" id="L451">            }, new Function&lt;Object, CompletableSource&gt;() {</span>
                @Override
                public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L454">                    return ps.ignoreElements();</span>
                }
<span class="fc" id="L456">            }, new Consumer&lt;Object&gt;() {</span>
                @Override
                public void accept(Object d) throws Exception {
<span class="fc" id="L459">                }</span>
            }, true)
<span class="fc" id="L461">            .test();</span>

<span class="fc" id="L463">            ps.onNext(1);</span>

<span class="fc" id="L465">            Runnable r1 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L468">                    to.cancel();</span>
<span class="fc" id="L469">                }</span>
            };

<span class="fc" id="L472">            Runnable r2 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L475">                    ps.onComplete();</span>
<span class="fc" id="L476">                }</span>
            };

<span class="fc" id="L479">            TestHelper.race(r1, r2);</span>
        }
<span class="fc" id="L481">    }</span>

    @Test
    public void errorDisposeRace() {
<span class="fc" id="L485">        RxJavaPlugins.setErrorHandler(Functions.emptyConsumer());</span>
        try {
<span class="fc bfc" id="L487" title="All 2 branches covered.">            for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>

<span class="fc" id="L489">                final PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L491">                final TestObserver&lt;Void&gt; to = Completable.using(new Callable&lt;Object&gt;() {</span>
                    @Override
                    public Object call() throws Exception {
<span class="fc" id="L494">                        return 1;</span>
                    }
<span class="fc" id="L496">                }, new Function&lt;Object, CompletableSource&gt;() {</span>
                    @Override
                    public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L499">                        return ps.ignoreElements();</span>
                    }
<span class="fc" id="L501">                }, new Consumer&lt;Object&gt;() {</span>
                    @Override
                    public void accept(Object d) throws Exception {
<span class="fc" id="L504">                    }</span>
                }, true)
<span class="fc" id="L506">                .test();</span>

<span class="fc" id="L508">                final TestException ex = new TestException();</span>

<span class="fc" id="L510">                Runnable r1 = new Runnable() {</span>
                    @Override
                    public void run() {
<span class="fc" id="L513">                        to.cancel();</span>
<span class="fc" id="L514">                    }</span>
                };

<span class="fc" id="L517">                Runnable r2 = new Runnable() {</span>
                    @Override
                    public void run() {
<span class="fc" id="L520">                        ps.onError(ex);</span>
<span class="fc" id="L521">                    }</span>
                };

<span class="fc" id="L524">                TestHelper.race(r1, r2);</span>
            }
        } finally {
<span class="fc" id="L527">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L529">    }</span>

    @Test
    public void emptyDisposeRace() {
<span class="fc bfc" id="L533" title="All 2 branches covered.">        for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>

<span class="fc" id="L535">            final PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L537">            final TestObserver&lt;Void&gt; to = Completable.using(new Callable&lt;Object&gt;() {</span>
                @Override
                public Object call() throws Exception {
<span class="fc" id="L540">                    return 1;</span>
                }
<span class="fc" id="L542">            }, new Function&lt;Object, CompletableSource&gt;() {</span>
                @Override
                public CompletableSource apply(Object v) throws Exception {
<span class="fc" id="L545">                    return ps.ignoreElements();</span>
                }
<span class="fc" id="L547">            }, new Consumer&lt;Object&gt;() {</span>
                @Override
                public void accept(Object d) throws Exception {

<span class="fc" id="L551">                }</span>
            }, true)
<span class="fc" id="L553">            .test();</span>

<span class="fc" id="L555">            Runnable r1 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L558">                    to.cancel();</span>
<span class="fc" id="L559">                }</span>
            };

<span class="fc" id="L562">            Runnable r2 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L565">                    ps.onComplete();</span>
<span class="fc" id="L566">                }</span>
            };

<span class="fc" id="L569">            TestHelper.race(r1, r2);</span>
        }
<span class="fc" id="L571">    }</span>

}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>